### ISSUE TITLE
Feature Request: abort multi_scan if the Xcode Scheme specifies parallelization 

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#101]
### Feature Request

Abort multi_scan if the Xcode Scheme specifies parallelization.

#### Motivation Behind Feature

`xcodebuild` does not output test results in a way that `xcpretty` can parse and produce valid `junit` report files. This means that `multi_scan` cannot determine which tests failed for subsequent re-runs.

#### Feature Description

I can imagine that we can query the Scheme using `xcodeproj` and there will be an entry specifying whether or not to parallelize the test runs. If that is found, `multi_scan` can simply raise an Exception.

#### Alternatives or Workarounds

There are two alternatives:
1. add code to parse test_result test summary plist files to determine whether or not there are failed tests. That may be a better, more reliable method of determining failures in the future.
2. use the `trainer` plugin to convert the plist files into junit files and then parse those.

**Comment by Jon889** [comment]
`-parallel-testing-enabled NO` can be passed to xcodebuild to override the scheme settings on parallelisation. not sure how that could get passed through scan.

**Comment by lyndsey-ferguson** [comment]
Super easy. Just a matter of time.

**Comment by lyndsey-ferguson** [comment]
Following up on that, I'd like to see if I could support Xcode's parallel testing enabled option.

**Comment by lyndsey-ferguson** [comment]
I will close this issue as the [Feature Idea: Run tests in parallel ](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/10) includes fixing the same issue and will be resolved in PR [Issue-10 parallel multi scan](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/pull/104)
