### ISSUE TITLE
Parallelization Bug: generated `test_result` bundles are deleted after completion

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#106]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

The parallelization beta 2 of `multi_scan` is deleting `test_result` bundles when it cleans up. These result bundles are stored in the intermediate "batch" directories for each simultaneous run of tests.

Some people use these test_result bundles for other purposes. They should use the `result_bundle` option, but that isn't very obvious.

##### Complete output when running fastlane, including the stack trace and command used

<img width="295" alt="Screen Shot 2019-06-21 at 2 32 57 PM" src="https://user-images.githubusercontent.com/6156112/59893668-c4f1cc80-9431-11e9-8548-3e4f39c9c62e.png">
When test starts it generates 4 different folders (i have asked to run 4 parallel tests). Which has the result_bundle as well. However when the test finished it cleans all 4 of these bundles (folders). I'm assuming if you don't clean it up, reporting could be generated using that?

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
@ishammoho your call to `xchtmlreport` must include a result bundle or an array of result bundles: https://github.com/Rightpoint/BonMot/blob/master/fastlane/actions/xchtmlreport.rb#L19

**Comment by lyndsey-ferguson** [comment]
Ok, I'm pretty sure that this behavior is correct. If you want a `result_bundle`, you must pass that option to `multi_scan`. It will copy the bundle to your output directory and collate them when complete. You can then look for that file and pass it to `xchtmlreport`.

**Comment by ishammoho** [comment]
I'm using result_bundle. however when the test run completes it doesn't collate the results properly. Generated report.html only shows results for the last completed test run block.

**Comment by szymon-kazmierczak** [comment]
I just wanted to say I'm seeing the same issue as ishammoho, only the last completed test run block's tests are reported (the xunit report, xcpretty html report and the .test_result bundle.

**Comment by lyndsey-ferguson** [comment]
Can you create a new issue? It may be due to how I am collating the results and you may instead need to just get a collection of test_result bundles to pass to the xchtmlreport tool.
