### ISSUE TITLE
"Error loading plugin...cannot load such file"

### ISSUE THREAD

**Issue by gmgchow** [lyndsey-ferguson/fastlane-plugin-test_center#12]
I tried installing this plugin into my project following the README instructions but when I try to run bundle exec fastlane test, I am getting the following error message. What can I do to fix this?

![screen shot 2018-01-25 at 11 53 27](https://user-images.githubusercontent.com/7692728/35368388-7c0aef82-01c6-11e8-95fb-b59243e8712b.png)

**Comment by zacoid55** [comment]
What does your Gemfile and Pluginfile look like, @gmgchow? Also what version of Ruby are you using?

**Comment by gmgchow** [comment]
Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

**Comment by gmgchow** [comment]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
[Gemfile.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/1663352/Gemfile.txt)
[Pluginfile.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/1663353/Pluginfile.txt)

**Comment by lyndsey-ferguson** [comment]
@gmgchow that's my fault. I accidentally left in a requirement on a gem that I use for debugging that I do not pull down as part of the gem spec. Try getting `v2.3.1`. @zacoid55 you probably have the gem because either I had it as part of the gem requirements, or you use it yourself.

**Comment by lyndsey-ferguson** [comment]
@gmgchow By the way, this plugin basically renders the `fastlane-plugin-setup_fragile_tests_for_rescan` obsolete.

**Comment by lyndsey-ferguson** [comment]
I ran this on a brand new fastlane and it worked fine. Closing.
