### ISSUE TITLE
Collated HTML reports display the tests outside of the coloured grid rows

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#126]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

The tests presented in the collated HTML report are displayed outside of the neatly generated table. There are no coloured rows.

<img width="598" alt="Screen Shot 2019-08-06 at 8 03 14 PM" src="https://user-images.githubusercontent.com/5741516/62586935-bcdcd780-b88d-11e9-803c-3f1a6b5b952f.png">

##### Complete output when running fastlane, including the stack trace and command used

N/A

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
@ishammoho [here is the call to `multi_scan`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L345)

**Comment by ishammoho** [comment]
Thanks for checking @lyndsey-ferguson

**Comment by lyndsey-ferguson** [comment]
Collation also does not remove failed tests when they later pass
<img width="1422" alt="html_collation" src="https://user-images.githubusercontent.com/5741516/63695409-a5d33a80-c7e6-11e9-8d19-f4e00a2ccdca.png">

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.8.5](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.8.5)
