### ISSUE TITLE
"only_testing" option no longer works with multiple test targets

### ISSUE THREAD

**Issue by stevenp** [lyndsey-ferguson/fastlane-plugin-test_center#132]
### New Regression Checklist

- [X] Updated `fastlane-plugin-test_center` to the latest version
- [X] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [X] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [X] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)
- [X] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Regression Information

- Breaking version: `3.8.0`
- Last working version: `3.7.0`

### Regression Description

When using the `only_testing` parameter against a scheme that has multiple test targets (for instance, `only_testing: ['TestTarget1', 'TestTarget2']`, this line is causing only the first testable to have its tests collected: https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/7c54f02dfa8037573d7f2ce23eb040da08260640/lib/fastlane/plugin/test_center/helper/test_collector.rb#L80

The reason for this is that `||=` is being used when the intention seems to be to use `+=`. Changing this operator and initializing `known_tests = []` fixes the issue.

I'll open a PR, but I wanted to log the issue so that you're aware of the regression.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.8.2](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.8.2)
