### ISSUE TITLE
Getting 'uninitialized constant' error.

### ISSUE THREAD

**Issue by rahulsharma2905** [lyndsey-ferguson/fastlane-plugin-test_center#151]
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

### Question Subject

I have a question about multi_scan action.

#### Question Description

I have 4 MacOS machines and the latest plugin is working fine on three of them. but on 4th one i am getting a weird error.

command executed:
bundle exec fastlane test_with_retry scheme:scheme1 destination:id=some_device_udid

Error received:
```Error loading plugin 'fastlane-plugin-test_center': uninitialized constant TestCenter::Helper::MultiScanManager::TestBatchWorker```

Stacktrace:
```
bundler: failed to load command: fastlane (PROJECT_DIR/vendor/bundle/ruby/2.3.0/bin/fastlane)
NameError: [!] uninitialized constant Fastlane::Actions::MultiScanAction::ScanHelper
Did you mean?  Fastlane::Helper
Did you mean?  Fastlane::Helper
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-594b49875bf2/lib/fastlane/plugin/test_center/actions/multi_scan.rb:132:in `use_scanfile_to_override_settings'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-594b49875bf2/lib/fastlane/plugin/test_center/actions/multi_scan.rb:108:in `prepare_for_testing'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-594b49875bf2/lib/fastlane/plugin/test_center/actions/multi_scan.rb:16:in `run'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  ../fastlane/Fastfile:16:in `block in parsing_binding'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
```
fastlane env:
[10:41:33]: Generating fastlane environment output, this might take a few seconds...
[10:41:34]: Error loading plugin 'fastlane-plugin-test_center': uninitialized constant TestCenter::Helper::MultiScanManager::TestBatchWorker
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                                                               |
| --------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| OS                          | 10.14.5                                                                                                             |
| Ruby                        | 2.3.7                                                                                                               |
| Bundler?                    | true                                                                                                                |
| Git                         | git version 2.20.1 (Apple Git-117)                                                                                  |
| Installation Source         | ~/jenkins/workspace/JOB_WS/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.14.5 (18F132)                                                                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib                                                      |
| OpenSSL Version             | LibreSSL 2.6.5                                                                                                      |
| Is contained                | false                                                                                                               |
| Is homebrew                 | false                                                                                                               |
| Is installed via Fabric.app | false                                                                                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                                         |
| Xcode Version               | 10.2.1                                                                                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
MY_XCODE_WORKSPACE_FILEPATH = File.absolute_path('../App.xcworkspace')
lane :test_with_retry do |options|
  test_run_block = lambda do |testrun_info|
    failed_test_count = testrun_info[:failed].size
    
    if failed_test_count > 0
      UI.important('The run of tests would finish with failures due to fragile tests here.')

      try_attempt = testrun_info[:try_count]
      if try_attempt < 3
        UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
      end
    end
  end
  
  result = multi_scan(
    workspace: MY_XCODE_WORKSPACE_FILEPATH,
    try_count: 3,
    fail_build: false,
    scheme: options[:scheme],
    destination: ["#{options[:destination]}"],
    testrun_completed_block: test_run_block,
    result_bundle: true,
    derived_data_path: options[:derived_data_path],
    output_directory: "#{options[:scheme]}_test_results"
  )
  unless result[:failed_testcount].zero?
    UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
  end
end

lane :test do |options|
  scheme_to_test = options[:scheme]
  device_id = options[:device_id]
  scan_options = {
  scheme: scheme_to_test,
  destination: "id=#{device_id}",
  output_directory: "App/#{scheme_to_test}_test_results",
  output_files: 'report.xml',
  output_types: 'junit',
  workspace: 'App.xcworkspace',
  result_bundle: true
}
begin
  retry_count ||= 0
  scan(scan_options)
  rescue => e
  UI.important("failure noted: #{e}")
  report_filepath =   File.absolute_path("../app/#{scheme_to_test}_test_results/report.xml")
unless File.exist?(report_filepath)
  raise e
 end
if (retry_count += 1) < 2
    setup_fragile_tests_for_rescan(
     project_path: File.absolute_path('../app.xcodeproj'),
     scheme: scheme_to_test,
     report_filepath: report_filepath
     )
    #clear_derived_data
    #reset_simulator_contents if retry_count > 1
    retry
   end
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                         | Version | Update-Status |
| ---------------------------------------------- | ------- | ------------- |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-test_center                    | 3.8.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                            | Version      |
| ---------------------------------------------- | ------------ |
| did_you_mean                                   | 1.0.0        |
| bundler                                        | 2.0.2        |
| io-console                                     | 0.4.5        |
| CFPropertyList                                 | 3.0.1        |
| public_suffix                                  | 2.0.5        |
| addressable                                    | 2.7.0        |
| atomos                                         | 0.1.3        |
| babosa                                         | 1.0.3        |
| claide                                         | 1.0.3        |
| colored                                        | 1.2          |
| colored2                                       | 3.1.2        |
| colorize                                       | 0.8.1        |
| highline                                       | 1.7.10       |
| commander-fastlane                             | 4.4.6        |
| declarative                                    | 0.0.10       |
| declarative-option                             | 0.1.0        |
| digest-crc                                     | 0.4.1        |
| unf_ext                                        | 0.0.7.6      |
| unf                                            | 0.1.4        |
| domain_name                                    | 0.5.20190701 |
| dotenv                                         | 2.7.5        |
| emoji_regex                                    | 1.0.1        |
| excon                                          | 0.67.0       |
| multipart-post                                 | 2.0.0        |
| faraday                                        | 0.15.4       |
| http-cookie                                    | 1.0.3        |
| faraday-cookie_jar                             | 0.0.6        |
| faraday_middleware                             | 0.13.1       |
| fastimage                                      | 2.1.7        |
| gh_inspector                                   | 1.1.3        |
| jwt                                            | 2.1.0        |
| memoist                                        | 0.16.0       |
| multi_json                                     | 1.13.1       |
| os                                             | 1.0.1        |
| signet                                         | 0.11.0       |
| googleauth                                     | 0.6.7        |
| httpclient                                     | 2.8.3        |
| mime-types-data                                | 3.2019.0904  |
| mime-types                                     | 3.3          |
| uber                                           | 0.1.0        |
| representable                                  | 3.0.4        |
| retriable                                      | 3.1.2        |
| google-api-client                              | 0.23.9       |
| google-cloud-env                               | 1.2.1        |
| google-cloud-core                              | 1.3.1        |
| google-cloud-storage                           | 1.16.0       |
| json                                           | 2.2.0        |
| mini_magick                                    | 4.9.5        |
| multi_xml                                      | 0.6.0        |
| plist                                          | 3.5.0        |
| rubyzip                                        | 1.3.0        |
| security                                       | 0.1.3        |
| naturally                                      | 2.2.0        |
| simctl                                         | 1.6.6        |
| slack-notifier                                 | 2.3.2        |
| terminal-notifier                              | 2.0.0        |
| unicode-display_width                          | 1.6.0        |
| terminal-table                                 | 1.8.0        |
| tty-screen                                     | 0.7.0        |
| tty-cursor                                     | 0.7.0        |
| tty-spinner                                    | 0.9.1        |
| word_wrap                                      | 1.0.0        |
| nanaimo                                        | 0.2.6        |
| xcodeproj                                      | 1.12.0       |
| rouge                                          | 2.0.7        |
| xcpretty                                       | 0.3.0        |
| xcpretty-travis-formatter                      | 1.0.0        |
| fastlane-plugin-setup_fragile_tests_for_rescan | 2.1.1        |
| xctest_list                                    | 1.1.8        |
| fastlane-plugin-test_center                    | 3.8.5        |
</details>

*generated on:* **2019-10-08**
</details>

Even ```bundle exec fastlane env``` command is throwing same error.

**Comment by rahulsharma2905** [comment]
I compared this machine's fastlane env output with a working machine's fastlane env output. And there is no difference in any plugin version.

**Comment by lyndsey-ferguson** [comment]
One thing I see that is suspicious is that your `fastlane-plugin-test_center` is using a version off of a commit, rather than an official release:
```
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-594b49875bf2/lib/fastlane/plugin/test_center/actions/multi_scan.rb:132:in `use_scanfile_to_override_settings'
```
Perhaps your `Gemfile.lock` file is referring to an old SHA that I force-pushed out of existence on a branch. (that's why I always ask people to remove their `Gemfile.lock` files when testing Pull Requests.

The directory above should refer to a specific version rather than what looks like a Git SHA.
```
  PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/fastlane-plugin-test_center-3.8.5/lib/fastlane/plugin/test_center/actions/multi_scan.rb:132:in `use_scanfile_to_override_settings'
```

**Comment by rahulsharma2905** [comment]
That's correct, i pointed it to my fork rather than official release. it is the same with official release too. 
I know this is some issue with my environment and not in plugin. I just want some direction, where should i look, what should i update if that's needed.

**Comment by lyndsey-ferguson** [comment]
What does your `Gemfile` look like? Is it pulling from your fork and branch correctly? Have you made any modifications to your local copy of the plugin in `PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/`?

**Comment by lyndsey-ferguson** [comment]
Oh, and you shouldn't need `fastlane-plugin-setup_fragile_tests_for_rescan` any longer. You can use this plugin's [`suppress_tests`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center#suppress_tests) action.

**Comment by lyndsey-ferguson** [comment]
> What does your `Gemfile` look like? Is it pulling from your fork and branch correctly?

Also, does the `594b49875bf2` SHA exist in the branch that you are pulling from? (I believe that is the SHA).

**Comment by rahulsharma2905** [comment]
answers:
- No i have not changed anything in PROJECT_DIR/vendor/bundle/ruby/2.3.0/bundler/gems/
- given SHA does exist in my repo.

Sorry for creating confusion because of my repo.

Now, i am trying to fetch official release.
I created a project with blank Fastfile.

Gemfile content:
```
source "https://rubygems.org"
  
gem "fastlane"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

Pluginfile content:
```gem 'fastlane-plugin-test_center'```

Fastlane env:
[11:27:48]: Generating fastlane environment output, this might take a few seconds...
[11:27:49]: Error loading plugin 'fastlane-plugin-test_center': uninitialized constant TestCenter::Helper::MultiScanManager::TestBatchWorker
[11:27:49]: It seems like you wanted to load some plugins, however they couldn't be loaded
[11:27:49]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | ~/new_proj/vendor/bundle/ruby/2.3.0/bin/fastlane               |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.8.5   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| bundler                     | 2.0.2        |
| io-console                  | 0.4.5        |
| CFPropertyList              | 3.0.1        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.7.0        |
| atomos                      | 0.1.3        |
| babosa                      | 1.0.3        |
| claide                      | 1.0.3        |
| colored                     | 1.2          |
| colored2                    | 3.1.2        |
| colorize                    | 0.8.1        |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| digest-crc                  | 0.4.1        |
| unf_ext                     | 0.0.7.6      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| dotenv                      | 2.7.5        |
| emoji_regex                 | 1.0.1        |
| excon                       | 0.67.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.4       |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.13.1       |
| fastimage                   | 2.1.7        |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| multi_json                  | 1.13.1       |
| os                          | 1.0.1        |
| signet                      | 0.11.0       |
| googleauth                  | 0.6.7        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2019.0904  |
| mime-types                  | 3.3          |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| google-cloud-env            | 1.2.1        |
| google-cloud-core           | 1.3.1        |
| google-cloud-storage        | 1.16.0       |
| json                        | 2.2.0        |
| mini_magick                 | 4.9.5        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.5.0        |
| rubyzip                     | 1.3.0        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.6        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.6.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.7.0        |
| tty-cursor                  | 0.7.0        |
| tty-spinner                 | 0.9.1        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.12.0       |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| xctest_list                 | 1.1.8        |
| fastlane-plugin-test_center | 3.8.5        |
</details>


*generated on:* **2019-10-09**
</details>

Still got the same error: Error loading plugin 'fastlane-plugin-test_center': uninitialized constant TestCenter::Helper::MultiScanManager::TestBatchWorker

**Comment by lyndsey-ferguson** [comment]
Is it possible that a bad copy of the gem is hanging around? What about if you run `gem uninstall fastlane-plugin-test_center` and then a `gem cleanup`, then `bundle install` where your project's `Gemfile` is?

**Comment by lyndsey-ferguson** [comment]
Also, my `Gemfile` has:
```
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
```
Instead of 
```
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```
Maybe that is an issue?

**Comment by rahulsharma2905** [comment]
tried both, still no luck.

**Comment by rahulsharma2905** [comment]
I am closing it for now, will open it again if i have some findings.

**Comment by lyndsey-ferguson** [comment]
Ok. I'm sure there is a solution. You did uninstalling right? Are you running fastlane with `bundle exec`?

**Comment by lyndsey-ferguson** [comment]
You don't have to give up! ✊
