### ISSUE TITLE
Result bundle is not collated in multi_scan.

### ISSUE THREAD

**Issue by rahulsharma2905** [lyndsey-ferguson/fastlane-plugin-test_center#154]
### Feature Request
Result bundles must be collated similar to html and junit reports when multi_scan action is used.
#### Motivation Behind Feature

junit and html reports generated by multi_scan action are collated and all test numbers are shown correctly, but when i look at result bundle, it only contains results for last iteration of test execution.
#### Feature Description

Say, I have 30 tests in some scheme, i have set retry count to 2 in multi_scan action, and 5 of these are failed in first iteration, then when i see the result bundle (or html generated by xchtmlreport plugin), it just contains tests executed in last iteration i.e. 5 tests.

#### Alternatives or Workarounds

If the multi_scan action generate separate result bundles for each iteration, then maybe we can collate it with collate_test_result_bundles action. but right now each iteration is replacing the previously generated result bundle.

**Comment by lyndsey-ferguson** [comment]
Hi @rahulsharma2905, it will be a lot of work to add proper collation to test result bundles. Xcode 11 adds a "merge" capability which I will be using once #145 is fixed. If you like, please navigate to that Issue for instructions on how to test it.

I am closing this as I will not be fixing test result collation for < Xcode 11.
