### ISSUE TITLE
Is there a way to capture console output without redirection?

### ISSUE THREAD

**Issue by jineshqa** [lyndsey-ferguson/fastlane-plugin-test_center#161]
### Question Checklist

- [X] Updated `fastlane-plugin-test_center` to the latest version
- [X] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [X] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [X] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

#### Question Description

When running `fastlane sweep --verbose` is there a way to capture console output without using redirection like `fastlane sweep --verbose > console.txt`?

**Comment by jineshqa** [comment]
Every I have to log a bug I have to redirect output which means I can't see the logs until everything is done. So would like a nice handy way to capture and see the log at the same time.

**Comment by lyndsey-ferguson** [comment]
Oh, then that is easy. Hold on.

**Comment by lyndsey-ferguson** [comment]
`bundle exec fastlane <your_lane_here> --verbose 2>&1 | tee /path/to/logfile.txt`

https://stackoverflow.com/a/18462920/71877

**Comment by jineshqa** [comment]
Thanks @lyndsey-ferguson, one more question. What does `clean` option on multi_scan do? Is it possible to delete app before each test case run?

**Comment by lyndsey-ferguson** [comment]
@jineshqa `clean` is passed straight to `scan` [here](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L135). From what I remember, `scan` simply adds the `clean` `buildaction` to the `xcodebuild` command which states (from a [man page I found online](https://www.manpagez.com/man/1/xcodebuild/)):

> clean       Remove build products and intermediate files from the
>                        build root (SYMROOT)

**Comment by jineshqa** [comment]
@lyndsey-ferguson One more question since there is no other way to chat with you and I don't want to create unnecessary tickets.

Is there anyway for you to uninstall app before each test case run? I used to do that with XCUiTest itself but with Xcode 11 it has become very very flaky :-(

**Comment by lyndsey-ferguson** [comment]
@jineshqa yes, you can use the [`:reinstall_app` option](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L90). Take a look at that and the other options.

**Comment by jineshqa** [comment]
That option only does it once not before each test case run.

Thanks,
Jinesh

**Comment by lyndsey-ferguson** [comment]
@jineshqa Each test run is a separate invocation of `scan`. That passes through `Scan::Runner.new.run`, that goes through [`test_app`](https://github.com/fastlane/fastlane/blob/b051f0e0dc0c93229752c2f0ae5216f7814e2179/scan/lib/scan/runner.rb#L25) then it runs the [`uninstall_app`](https://github.com/fastlane/fastlane/blob/b051f0e0dc0c93229752c2f0ae5216f7814e2179/scan/lib/scan/runner.rb#L46) if that option is on.

If it is not running through that for each test run, can you create an Issue?

**Comment by lyndsey-ferguson** [comment]
One thing: I recommend not using this option with parallelize as it will uninstall on all devices. Even in the middle of a run.
