### ISSUE TITLE
Feature: Suppress one or more targets

### ISSUE THREAD

**Issue by fishercraigj** [lyndsey-ferguson/fastlane-plugin-test_center#17]
I have multiple targets that I use for Unit Tests and UI Testing. Any way to add a feature that would allow us to suppress tests against one or more targets?

**Comment by lyndsey-ferguson** [comment]
It depends on what you're looking for. You can use the `suppress_tests` action to identify which tests you want to suppress in the scheme itself and it will go to the right target. Say for example you have two targets, `AtomicTests` and `AtomicUITests`. You can suppress individual tests or entire test suites by passing in to to the action the tests in the format that xcodebuild wants:
```
suppress_tests(
    xcodeproj: 'AtomicBoy/AtomicBoy.xcodeproj',
    tests: [
      'AtomicTests/UraniumTestSuite', 
      'AtomicTests/PlutoniumTestSuite/testHeatDectector',     
      'AtomicUITests/LauncherTestSuite/testLaunchRequiresTwoButtons' 
    ],
    scheme: 'Professor'
  )
```
Is this what you're looking for?

**Comment by fishercraigj** [comment]
Okay perfect.  I didn't notice that action at first glance.

Amazing framework btw!

**Comment by lyndsey-ferguson** [comment]
Thank you @fishercraigj! I will close this issue and if you have any problem running this action, create a new Issue.
