### ISSUE TITLE
When parallel run is selected, only last simulator failure is retried again in Xcode11.

### ISSUE THREAD

**Issue by selin194** [lyndsey-ferguson/fastlane-plugin-test_center#181]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [ ] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
I want to run our UI Tests on CI by using jenkins. 
We are using `Xcode11` with version `11.2.1`
When I use `multi_scan` with the following parameters:
         ```  result = multi_scan(
                 workspace: 'my.xcworkspace',
                 try_count: 3,
                 fail_build: false,
                 scheme: 'UITests',
                 testrun_completed_block: test_run_block,
                 parallel_testrun_count: 2,
                 device: 'iPhone 8 Plus'
                )```

We have 2 test suites with 2 different test cases on them.
When I follow results on CI, multi_scan creates 2 different batches. On each batch 2 test cases are running. 
2 iPhone 8 clones are created and tests are started to run. 
2 test suites have 1 test cases that need to fail. (For testing purpose I arranged them like they need to fail by adding this line to the cases `XCAssertEqual(1,2)`)
However, only the last batch is retried. And the first failed test case is never retried on `batch 1`
 Do you have any idea about this? @lyndsey-ferguson, Thank you.

<!-- Please include which _test_center_ action you are using. For example, multi_scan, tests_from_junit, etc. -->
<!-- Please include what's happening, expected behavior, and any relevant code samples -->

##### Complete output when running fastlane, including the stack trace and command used
<!-- You can use: `--verbose --capture_output` as the last commandline arguments to get that collected for you -->

<!-- The output of `--verbose --capture_output` could contain sensitive data such as application ids, certificate ids, passwords, authentication tokens, or email addreses, Please make sure you double check the output and replace anything sensitive you don't wish to submit in the issue -->

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<!-- Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used the `--capture_output` option, please remove this block as it is already included there. -->

test_center -> `3.8.15`
Xcode version ->  `11.2.1`
jenkins version -> `2.176.3`

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
Hello @selin194, thank you for the bug report. I haven't seen this before. Can you run your fastlane with the `--verbose` flag and attach the logs from the console to this Issue?

The only thing that I can think of is if the the first batch had some sort of error that would cause it to crash.

**Comment by selin194** [comment]
+-------------------------+-----------------------------------------------+
|              [0;32;49mSummary for multi_scan (test_center v3.8.15)[0m               |
+-------------------------+-----------------------------------------------+
| try_count               | 3                                             |
| testrun_completed_block | #<Proc:0x007f9c8b25d120@Fastfile:56 (lambda)> |
| parallel_testrun_count  | 2                                             |
+-------------------------+-----------------------------------------------+

ERROR [2019-12-16 10:16:10.78]: [1;34;49mUsing deprecated option: '--custom_report_file_name' (Use `--output_files` instead)[0m
WARN [2019-12-16 10:16:10.79]: [0;33;49mScanfile found: overriding multi_scan options with it's values.[0m
DEBUG [2019-12-16 10:16:10.79]: Building the project in preparation for multi_scan testing
ERROR [2019-12-16 10:16:10.79]: [1;34;49mUsing deprecated option: '--custom_report_file_name' (Use `--output_files` instead)[0m
INFO [2019-12-16 10:16:10.79]: [0;32;49mSuccessfully loaded '/Users/jenkins/.jenkins/workspace/retry-failed-tests/folder/fastlane/Scanfile' 📄[0m

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| scheme               | UITests     |
| workspace            | my.xcworkspace   |
| device               | iPhone 8 Plus       |
| force_quit_simulator | true                |
| reset_simulator      | true                |
| result_bundle        | output.xcresult     |
| fail_build           | false               |
+----------------------+---------------------+

ERROR [2019-12-16 10:16:10.82]: [0;31;49mCouldn't find specified scheme 'UITests'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3[0m
INFO [2019-12-16 10:16:10.82]: [0;36;49m$ xcodebuild -showBuildSettings -workspace my.xcworkspace -scheme UITests[0m
DEBUG [2019-12-16 10:16:13.67]: Fetching available simulator devices
DEBUG [2019-12-16 10:16:13.84]: Detected derived data path '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv'

+------------------------------------------------+---------------------------------------------------------------------------------------+
|                                                        [0;32;49mSummary for scan 2.137.0[0m                                                        |
+------------------------------------------------+---------------------------------------------------------------------------------------+
| workspace                                      | my.xcworkspace                                                                     |
| fail_build                                     | false                                                                                 |
| scheme                                         | UITests                                                                       |
| device                                         | iPhone 8 Plus                                                                         |
| skip_detect_devices                            | false                                                                                 |
| force_quit_simulator                           | true                                                                                  |
| reset_simulator                                | true                                                                                  |
| reinstall_app                                  | false                                                                                 |
| clean                                          | false                                                                                 |
| open_report                                    | false                                                                                 |
| output_directory                               | ./fastlane/test_output                                                                |
| buildlog_path                                  | ~/Library/Logs/scan                                                                   |
| include_simulator_logs                         | false                                                                                 |
| derived_data_path                              | /Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv |
| should_zip_build_products                      | false                                                                                 |
| result_bundle                                  | output.xcresult                                                                       |
| use_clang_report_name                          | false                                                                                 |
| disable_concurrent_testing                     | false                                                                                 |
| skip_build                                     | false                                                                                 |
| build_for_testing                              | true                                                                                  |
| slack_use_webhook_configured_username_and_icon | false                                                                                 |
| slack_username                                 | fastlane                                                                              |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                        |
| skip_slack                                     | false                                                                                 |
| slack_only_on_failure                          | false                                                                                 |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                                     |
| output_types                                   | html,junit                                                                            |
| xcode_path                                     | /Applications/Xcode.app                                                               |
+------------------------------------------------+---------------------------------------------------------------------------------------+
DEBUG [2019-12-16 10:16:13.85]: Before building, removing pre-existing xctestrun files: []
DEBUG [2019-12-16 10:16:13.86]: Fetching available simulator devices
INFO [2019-12-16 10:16:14.01]: Resetting iPhone 8 Plus
INFO [2019-12-16 10:16:14.13]: [0;36;49m$ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace my.xcworkspace -scheme UITests -destination 'platform=iOS Simulator,id=C14CB84F-0BD2-4D01-B377-A5C787567F0B' -derivedDataPath '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv' -resultBundlePath './fastlane/test_output/UITests.test_result' build-for-testing | tee '/Users/jenkins/Library/Logs/scan/UITests-UITests.log' | xcpretty  --report html --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/report.html' --report junit --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/folder/fastlane/test_output/report.junit' --report junit --output '/var/folders/cd/xt1fd3c965nd6bvy9cckhw1c0000gn/T/junit_report20191216-9515-gxkzyr' [0m

**Comment by selin194** [comment]
+-------------------------+-----------------------------------------------+
| �[0;32;49mSummary for multi_scan (test_center v3.8.15)�[0m |
+-------------------------+-----------------------------------------------+
| try_count | 3 |
| testrun_completed_block | #<Proc:0x007f9c8b25d120@Fastfile:56 (lambda)> |
| parallel_testrun_count | 2 |
+-------------------------+-----------------------------------------------+

ERROR [2019-12-16 10:16:10.78]: �[1;34;49mUsing deprecated option: '--custom_report_file_name' (Use --output_files instead)�[0m
WARN [2019-12-16 10:16:10.79]: �[0;33;49mScanfile found: overriding multi_scan options with it's values.�[0m
DEBUG [2019-12-16 10:16:10.79]: Building the project in preparation for multi_scan testing
ERROR [2019-12-16 10:16:10.79]: �[1;34;49mUsing deprecated option: '--custom_report_file_name' (Use --output_files instead)�[0m
INFO [2019-12-16 10:16:10.79]: �[0;32;49mSuccessfully loaded '/Users/jenkins/.jenkins/workspace/retry-failed-tests/folder/fastlane/Scanfile' 📄�[0m

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| scheme | UITests |
| workspace | my.xcworkspace |
| device | iPhone 8 Plus |
| force_quit_simulator | true |
| reset_simulator | true |
| result_bundle | output.xcresult |
| fail_build | false |
+----------------------+---------------------+

ERROR [2019-12-16 10:16:10.82]: �[0;31;49mCouldn't find specified scheme 'UITests'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3�[0m
INFO [2019-12-16 10:16:10.82]: �[0;36;49m$ xcodebuild -showBuildSettings -workspace my.xcworkspace -scheme UITests�[0m
DEBUG [2019-12-16 10:16:13.67]: Fetching available simulator devices
DEBUG [2019-12-16 10:16:13.84]: Detected derived data path '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv'

+------------------------------------------------+---------------------------------------------------------------------------------------+
| �[0;32;49mSummary for scan 2.137.0�[0m |
+------------------------------------------------+---------------------------------------------------------------------------------------+
| workspace | my.xcworkspace |
| fail_build | false |
| scheme | UITests |
| device | iPhone 8 Plus |
| skip_detect_devices | false |
| force_quit_simulator | true |
| reset_simulator | true |
| reinstall_app | false |
| clean | false |
| open_report | false |
| output_directory | ./fastlane/test_output |
| buildlog_path | ~/Library/Logs/scan |
| include_simulator_logs | false |
| derived_data_path | /Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv |
| should_zip_build_products | false |
| result_bundle | output.xcresult |
| use_clang_report_name | false |
| disable_concurrent_testing | false |
| skip_build | false |
| build_for_testing | true |
| slack_use_webhook_configured_username_and_icon | false |
| slack_username | fastlane |
| slack_icon_url | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png |
| skip_slack | false |
| slack_only_on_failure | false |
| xcodebuild_command | env NSUnbufferedIO=YES xcodebuild |
| output_types | html,junit |
| xcode_path | /Applications/Xcode.app |
+------------------------------------------------+---------------------------------------------------------------------------------------+
DEBUG [2019-12-16 10:16:13.85]: Before building, removing pre-existing xctestrun files: []
DEBUG [2019-12-16 10:16:13.86]: Fetching available simulator devices
INFO [2019-12-16 10:16:14.01]: Resetting iPhone 8 Plus
INFO [2019-12-16 10:16:14.13]: �[0;36;49m$ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace my.xcworkspace -scheme UITests -destination 'platform=iOS Simulator,id=C14CB84F-0BD2-4D01-B377-A5C787567F0B' -derivedDataPath '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv' -resultBundlePath './fastlane/test_output/UITests.test_result' build-for-testing | tee '/Users/jenkins/Library/Logs/scan/UITests-UITests.log' | xcpretty --report html --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/report.html' --report junit --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/folder/fastlane/test_output/report.junit' --report junit --output '/var/folders/cd/xt1fd3c965nd6bvy9cckhw1c0000gn/T/junit_report20191216-9515-gxkzyr' �[0m

**Comment by selin194** [comment]
Hey thank you for responding, I rerun the job again with --verbose flag and I see: 
[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:23:11.95]: Batch #1 incrementing retry count to 1
[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:23:11.95]: Scan found failing tests for batch #1
[0;34;49m[worker 1] [0mWARN [2019-12-16 10:23:11.97]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:23:11.97]: [0;32;49m-----------------------------------------------------[0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:23:11.97]: [0;32;49mSince we are using :multi_scan, we can re-run just those failing tests![0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:23:11.97]: [0;32;49m-----------------------------------------------------[0m

[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:24:28.97]: Batch #1 incrementing retry count to 2
[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:24:28.97]: Scan found failing tests for batch #1
[0;34;49m[worker 1] [0mWARN [2019-12-16 10:24:28.97]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:24:28.97]: [0;32;49m-----------------------------------------------------[0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:24:28.97]: [0;32;49mSince we are using :multi_scan, we can re-run just those failing tests![0m
[0;34;49m[worker 1] [0mINFO [2019-12-16 10:24:28.97]: [0;32;49m-----------------------------------------------------[0m
[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:25:47.51]: Batch #1 incrementing retry count to 3
[0;34;49m[worker 1] [0mDEBUG [2019-12-16 10:25:47.51]: Scan found failing tests for batch #1
[0;34;49m[worker 1] [0mWARN [2019-12-16 10:25:47.51]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m

[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:22:24.92]: Batch #2 incrementing retry count to 1
[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:22:24.92]: Scan found failing tests for batch #2
[0;32;49m[worker 2] [0mWARN [2019-12-16 10:22:24.94]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m
[0;32;49m[worker 2] [0mINFO [2019-12-16 10:22:24.95]: [0;32;49m-----------------------------------------------------[0m
[0;32;49m[worker 2] [0mINFO [2019-12-16 10:22:24.95]: [0;32;49mSince we are using :multi_scan, we can re-run just those failing tests![0m

[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:23:08.35]: Batch #2 incrementing retry count to 2
[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:23:08.35]: Scan found failing tests for batch #2
[0;32;49m[worker 2] [0mWARN [2019-12-16 10:23:08.35]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m
[0;32;49m[worker 2] [0mINFO [2019-12-16 10:23:08.35]: [0;32;49m-----------------------------------------------------[0m
[0;32;49m[worker 2] [0mINFO [2019-12-16 10:23:08.35]: [0;32;49mSince we are using :multi_scan, we can re-run just those failing tests![0m
[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:23:46.86]: Batch #2 incrementing retry count to 3
[0;32;49m[worker 2] [0mDEBUG [2019-12-16 10:23:46.86]: Scan found failing tests for batch #2
[0;32;49m[worker 2] [0mWARN [2019-12-16 10:23:46.86]: [0;33;49mThe run of tests would finish with failures due to fragile tests here.[0m

Which is expected. I do not see these logs without verbose, could it be related with `--verbose` flag? I rerun the job again, and waiting for its result for the second time. Maybe for that run for the fisrt batch I received an error, and can not see that error. Not sure about this.

**Comment by lyndsey-ferguson** [comment]
One thing, can you re-run this without the color-codes? It is hard to read.
Here is how I would do it:

```sh
FASTLANE_DISABLE_COLORS=1 bundle exec fastlane <insert_your_lane_name_here> --verbose
```

When you write:
> Which is expected

Are you stating that things are working? The logs do not list which tests were run, nor does it list how `xcodebuild` was called, etc. There is a lot missing from the logs.

I'd like to see how this works from the moment that `fastlane` is called on the command line until the command ends. I need to see what is happening in order to be able to start happening.

With regards to the question:
>  I do not see these logs without verbose, could it be related with --verbose flag?

I don't know, it doesn't seem right though. These logs are not what I would expect (except for the `DEBUG` prefixes. With verbose, there is a **log** more data.

**Comment by lyndsey-ferguson** [comment]
@selin194 any progress on my request above?

**Comment by selin194** [comment]
Hey @lyndsey-ferguson, sorry for the late response. Unluckily I am not allowed to share all of the logs publicly. However, I can share the table that summaries the process. Thank you so much for your interest and support!

**Comment by lyndsey-ferguson** [comment]
I need the logs, can you not anonymize/edit them to make them generic?

**Comment by selin194** [comment]
```
[0;32;49m[worker 2] [0m
[0;32;49m[worker 2] [0mDEBUG [2019-12-18 12:00:32.74]: Fetching available simulator devices
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:32.92]: Resetting iPhone 8 Plus
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:33.04]: [0;36;49m$ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -destination 'platform=iOS Simulator,id=A6D8B224-F75C-4A8A-84EF-0C641C58DE1E' -derivedDataPath '/var/folders/cd/xt1fd3c965nd6bvy9cckhw1c0000gn/T/derived_data_path20191218-44606-1t5g9e6-worker-2' -disable-concurrent-testing -xctestrun '/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv/Build/Products/UITests_iphonesimulator13.2-x86_64.xctestrun'  -parallel-testing-enabled NO -only-testing:UITests/TestSuite1/testCase1 -only-testing:UITests/TestSuite2/testCase1 test-without-building | tee '/Users/jenkins/Library/Logs/scan/worker-2-logs/UITests-UITests.log' | xcpretty  --report junit --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml' --report html --output '/Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/UITests-batch-2/report-2.html' --report junit --output '/var/folders/cd/xt1fd3c965nd6bvy9cckhw1c0000gn/T/junit_report20191218-54292-1qmpu8l' [0m
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:33.04]: ▸ [0;35;49mLoading...[0m
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:34.10]: ▸ [0;35;49mxcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.[0m
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:34.11]: ▸ [0;35;49m	Reason: Cannot load xctestrun file (/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv/Build/Products/UITests_iphonesimulator13.2-x86_64.xctestrun): The file “UITests_iphonesimulator13.2-x86_64.xctestrun” couldn’t be opened because there is no such file.[0m
[0;32;49m[worker 2] [0mINFO [2019-12-18 12:00:34.11]: ▸ [0;35;49m	Recovery suggestion: Consult the xctestrun file format documentation using `man xcodebuild.xctestrun`.[0m
[0;32;49m[worker 2] [0mxcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
[0;32;49m[worker 2] [0m	Reason: Cannot load xctestrun file (/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv/Build/Products/UITests_iphonesimulator13.2-x86_64.xctestrun): The file “UITests_iphonesimulator13.2-x86_64.xctestrun” couldn’t be opened because there is no such file.
[0;32;49m[worker 2] [0m	Recovery suggestion: Consult the xctestrun file format documentation using `man xcodebuild.xctestrun`.
[0;32;49m[worker 2] [0mERROR [2019-12-18 12:00:34.12]: [0;31;49mExit status: 70[0m
[0;32;49m[worker 2] [0mDEBUG [2019-12-18 12:00:34.13]: Batch #2 incrementing retry count to 2
[0;32;49m[worker 2] [0mDEBUG [2019-12-18 12:00:34.13]: Scan unable to test for batch #2
[0;32;49m[worker 2] [0mERROR [2019-12-18 12:00:34.13]: 
[0;32;49m[worker 2] [0mError building/testing the application. See the log above.
[0;32;49m[worker 2] [0m["/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/scan/lib/scan/error_handler.rb:46:in `handle_build_error'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/scan/lib/scan/runner.rb:70:in `block in test_app'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/scan/lib/scan/runner.rb:61:in `test_app'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/scan/lib/scan/runner.rb:22:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:59:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:45:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb:18:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/parallel_test_batch_worker.rb:49:in `block in run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/parallel_test_batch_worker.rb:45:in `fork'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/parallel_test_batch_worker.rb:45:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:143:in `block in run_test_batches'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each_with_index'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `run_test_batches'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:53:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/actions/multi_scan.rb:29:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'", "Fastfile:66:in `block (2 levels) in parsing_binding'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'", "/Users/jenkins/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'"]
[0;32;49m[worker 2] [0mDEBUG [2019-12-18 12:00:34.13]: All tests passed for batch 2? false
DEBUG [2019-12-18 12:00:34.25]: Collating results for all batches
DEBUG [2019-12-18 12:00:34.25]: ReportCollator collating
DEBUG [2019-12-18 12:00:34.25]: Collating junit report files ["/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-1/report.xml", "/Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/UITests-batch-2/report.xml", "/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml"]
DEBUG [2019-12-18 12:00:34.25]: collate_junit_reports with ["/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-1/report.xml", "/Users/jenkins/.jenkins/workspace/ios-retry-failed-tests/fastlane/test_output/UITests-batch-2/report.xml", "/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml"]
DEBUG [2019-12-18 12:00:34.28]: > collating last report file /Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml
DEBUG [2019-12-18 12:00:34.32]: < collating last report file /Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml
DEBUG [2019-12-18 12:00:34.32]: > collating last report file /Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/UITests-batch-2/report-2.xml
DEBUG [2019-12-18 12:00:34.32]: < collating last report file /Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.xml
DEBUG [2019-12-18 12:00:34.32]: Collating html report files ["/Users/jenkins/.jenkins/workspace/retry-failed-tests/ipad/fastlane/test_output/UITests-batch-1/report.html", "/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report.html", "/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report-2.html"]
WARN [2019-12-18 12:00:34.34]: [0;33;49m'/Users/jenkins/.jenkins/workspace/retry-failed-tests/fastlane/test_output/UITests-batch-2/report.html' is malformed. Attempting to repair it[0m
````

An error occurred attempting to retry the failed test cases, but this time for the second batch. Do you have any idea and these logs are enough to catch failure reason?

**Comment by lyndsey-ferguson** [comment]
This is the error:
```
Reason: Cannot load xctestrun file (/Users/jenkins/Library/Developer/Xcode/DerivedData/project-bjteyhkzrfodogfwryunhqtaljxv/Build/Products/UITests_iphonesimulator13.2-x86_64.xctestrun): The file “UITests_iphonesimulator13.2-x86_64.xctestrun” couldn’t be opened because there is no such file.
```

`xcodebuild` cannot run the tests because the necessary `xctestrun` file is missing.

If you can include the full log, I can review the steps when `multi_scan` will build the app and then find the `xctestrun` file.  By giving me only snippets of the log, it forces me to guess and the whole process of solving this issue is delayed unnecessarily.

Please 🙏, provide the complete log. You can use a global text search and replace to remove any sensitive data you are concerned about exposing.

**Comment by lyndsey-ferguson** [comment]
@selin194 any update on this?

**Comment by selin194** [comment]
Hey @lyndsey-ferguson, Jenkins stores the last 100 job builds and when I checked each build error for these jobs I realized that we did not receive such an error :(

**Comment by lyndsey-ferguson** [comment]
@selin194 sounds great. I'll close this Issue, but don't worry, if you encounter the issue again and have the logs, you can attach them to the Issue. 

I will get a notice and I will then re-open the issue. Happy New Year!
