### ISSUE TITLE
Wrong retry test count log

### ISSUE THREAD

**Issue by andreaantonioni** [lyndsey-ferguson/fastlane-plugin-test_center#190]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
When I use `mult_scan` with the retry `try_count` > 1,  I see that in the second `scan` (when rerunning failed tests), I read this log:
`Starting scan #2 with 44 tests for batch #4`
but actually 44 aren't the number of failed tests but the number of failed assertions.

**Comment by lyndsey-ferguson** [comment]
Hello @andreaantonioni, can you please include the logs using the `--verbose` flag when running the fastlane?

**Comment by lyndsey-ferguson** [comment]
Closed issue due to lack of activity (and logs).
