### ISSUE TITLE
test_center 2.5.0

### ISSUE THREAD

**Issue by fishercraigj** [lyndsey-ferguson/fastlane-plugin-test_center#20]
During my fastlane runs, I was getting messages that there was a newer version of test_center which was 2.5.0.  So I said cool, and upgraded.  The only problem is now that when ever I run an action it tells me that there are no actions available.  When I run "fastlane action multi_scan, I now get this: 

`[✔] 🚀
[00:55:42]: fastlane detected a Gemfile in the current directory
[00:55:42]: however it seems like you don't use bundle exec
[00:55:42]: to launch fastlane faster, please use
[00:55:42]:
[00:55:42]: $ bundle exec fastlane action multi_scan
[00:55:42]:
[00:55:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:55:42]: Error loading plugin 'fastlane-plugin-test_center': cannot load such file -- pry-byebug
[00:55:42]: It seems like you wanted to load some plugins, however they couldn't be loaded
[00:55:42]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-----------------------------+---------+------------------+
|                       Used plugins                       |
+-----------------------------+---------+------------------+
| Plugin                      | Version | Action           |
+-----------------------------+---------+------------------+
| fastlane-plugin-test_center | 2.5.0   | No actions found |
+-----------------------------+---------+------------------+

Loading documentation for multi_scan:

Couldn't find action for the given filter.
==========================================`

I attempted to reinstall (hoping to get back to 2.4.4) to see if that solved the problem by removing the line added to the plugin file and also doing a "gem uninstall fastlane-plugin-test_center".  Upon reinstalling, it agains adds 2.5.0.

Can you point me in the right direction as to how to get back to 2.4.4 when everything is working?  I also noticed that this version is flagged as your latest release so I'm wondering if I corrupted something by installing 2.5.0 when I was prompted by Fastlane.

**Comment by fishercraigj** [comment]
Sorry, figured it out.  In my plugin file I did this: 
gem 'fastlane-plugin-test_center', "2.4.4"

Then removed the 2.5.0 gem.  

All good now!

**Comment by lyndsey-ferguson** [comment]
Sorry, my fault:
`[00:55:42]: Error loading plugin 'fastlane-plugin-test_center': cannot load such file -- pry-byebug`
I cleaned it up and released v2.5.1.

**Comment by lyndsey-ferguson** [comment]
This will not happen again. I changed my gem releasing to prevent pry-byebug to be required.

**Comment by fishercraigj** [comment]
Nice!  Always helps having other people using your tooling so you can find these little things.  :)

**Comment by lyndsey-ferguson** [comment]
Yes, it has been fantastic!
