### ISSUE TITLE
Getting bundler: failed to load command inconsistently

### ISSUE THREAD

**Issue by jordan-romeroporter-earnin** [lyndsey-ferguson/fastlane-plugin-test_center#210]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

Getting a Failed to load command error when running multi_scan. This doesn't happen consistently, so it makes understanding why it's happening that much more confusing.
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneTestFailure: [!] Tests have failed
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/interface.rb:172:in `test_failure!'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.8.15/lib/fastlane/plugin/test_center/actions/multi_scan.rb:35:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:121:in `block in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:107:in `block (2 levels) in parsing_binding'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre>Same as here: https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/209</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
```ruby
FastlaneCore::Interface::FastlaneTestFailure: [!] Tests have failed
  /Users/distiller/project/vendor/bundle/ruby/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/interface.rb:172:in `test_failure!'
```
Is telling you that tests failed. If you set [`:fail_build`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/v3.8.15/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L34) to `false`, it won't throw when your tests failed.

**Comment by lyndsey-ferguson** [comment]
As to why you're getting this:
```
bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/2.6.0/bin/fastlane)

```
I'm not sure yet.

**Comment by lyndsey-ferguson** [comment]
This has a similar pattern:
https://github.com/fastlane/fastlane/issues/11071

**Comment by jordan-romeroporter-earnin** [comment]
So for the first part, we need the fail_build so that way it returns the correct exit code & prevents the flow of execution on our CI

**Comment by jordan-romeroporter-earnin** [comment]
For your follow up - the changes we made were double checked and didn't seem to have any syntax issues - however we did include --verbose into every single run of multi_scan...so I wonder if that's inducing it?

**Comment by lyndsey-ferguson** [comment]
Try without it and let me know if that changes anything

**Comment by jordan-romeroporter-earnin** [comment]
We're confident that's the problem.

**Comment by jordan-romeroporter-earnin** [comment]
However, is there a way to keep --verbose without it failing?
