### ISSUE TITLE
Can i retry a class of tests if one of its tests fails, rather than just retrying the single test?

### ISSUE THREAD

**Issue by hannahw1ll1ams** [lyndsey-ferguson/fastlane-plugin-test_center#224]
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

Hi!

I'm using multiscan to retry any UI tests that are failing. Because of the way my UI tests are set up though, if one test fails in its particular class I want to retry the whole class instead of just the failing test. I am struggling to find out if this is an option for multiscan?

Thanks

**Comment by lyndsey-ferguson** [comment]
It seems that you're looking to manage what tests are re-run as in [this feature request](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/176). OR, you're looking for an option ALWAYS retry the entire testcase. Either way, no multi_scan doesn't supply this out of the box..

You could use a `test_run_block` to get the junit xml report file paths and remove it between test runs. That callback is called before the next set of tests is run.

https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/d37839b68a63cd7b2cdeff1df2117aaea99d1ce6/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L414

That may work, or it may crash. You may want to use REXML to remove the children of the testsuites element...

**Comment by lyndsey-ferguson** [comment]
Closing this Issue as I haven't received a response from the author and I don't think there is any more to discuss: we have a workaround, and there is already a feature request.
