### ISSUE TITLE
Enhancement: multi_scan to return results

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#23]
It would be nice if `multi_scan` could return information on:
- what the final result was (pass|fail)
- where the report file(s) are
- how many times `scan` was "re-tried"

**Comment by fishercraigj** [comment]
I'd take this story in a heartbeat!  But I do this manually with variables so it's not that big of a deal ATM.

There's some additional stuff that I personally use.  Not saying everyone will, but I use it this way mainly for the purpose of logging out to my CI.  If I could be so bold as to add to this list, I'd add the following:

- Return values of ALL mutl_scan specific variables that where passed at initialization.  IE: devices, scheme, devices, etc.
- Return count of total count of tests ran

**Comment by lyndsey-ferguson** [comment]
If I passed in the variables, why would I want them back? Or, if I wrote a `lane` that called `multi_scan`, I would know what variables I am passing in to the action.

I can see returning the count of tests, maybe also which tests were _fragile_.

**Comment by fishercraigj** [comment]
Yup, I totally here you.  I was just looking at it as a "one stop shop" for anything multi_scan related.

If you want to get a little cray-cray on fragile tests results, you could add on which pass of you try_count that said test passed.

My app has some issues with flaky networks.  Without physically sitting and watch the actual test run live, I'm always curious as to which try the test passed on.  Keep in mind I don't use the junit results.

**Comment by zacoid55** [comment]
@fishercraigj how do you get the variables? I'm having a hard time getting them out for CI purposes

**Comment by lyndsey-ferguson** [comment]
I'm not sure what variables you're looking for, but if you want to get the tests that failed/passed, you can call the [`tests_from_junit`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/tests_from_junit.rb#L46) action, pointing it at your junit file to get the list of tests that passed and failed.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.0.1](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.0.1)
