### ISSUE TITLE
TestReporting

### ISSUE THREAD

**Issue by fishercraigj** [lyndsey-ferguson/fastlane-plugin-test_center#24]
I still hate that GitHub doesn't have private messages but figured I'd just drop you a line here.  ;)

Since you and I seem to do a lot of the same similar things in our professional lives you came to my mind when I was looking at this JIRA story that's been looming for awhile.  I was curious what you are (if you are) for auto generated reporting to a test case repository and do you do it cross platform?  IE: Web, Android, and iOS.

For the most part, i've always used TestRail.  Being a way more knowledgeable in the iOS arena, I developed an internal iOS framework that auto gens the reports to test rails but like that implies that, it only works for iOS.  I should rewrite this in swift and make it available to other but that is a whole different subject.

I want to do something with FastLane that, in the least, could also work from Android especially since iOS and Android are pulling from the same test case repository.

Just curious about your thoughts before I broadcast this out to our wider FastLane community.

**Comment by lyndsey-ferguson** [comment]
You use TestRail to collect the automated junit report files? I haven't heard of it before, and glancing at their [webpage](http://www.gurock.com/testrail/), it seems this is mostly used to track manual testing (?).

If you're targeting junit test result trends, that I can write about. We are just wrapping up logging our test and job metrics. We are using [Grafana](https://grafana.com) to display our metrics with a mixture of AWS S3, [logstash](https://www.elastic.co/products/logstash), [elasticsearch](https://www.elastic.co), and [Prometheus+node_exporter](https://prometheus.io) as the backend.

This allows us to log _all_ of our test trends and it has been very interesting.

So, you may want to take a look at that beforehand to see if it already does what you want to do.

**Comment by fishercraigj** [comment]
Thanks for your thoughts @lyndsey-ferguson!  I'll definitely take a peek at what you're doing and see what I can glean from it.  Gives me an excuse to go back and play in the devops game again.  :)

Aside for some quick logging of results to our internal messaging system, I'm not using junit files for anything ATM.  My reporting framework is 100% on the iOS side subclassed from XCUITest.  In a nutshell, I take the test results from XCUITests and send them out through the TestRail API.  There's obviously a lot of in between development but you probably get my drift.

I've been using this framework for years with a lot of success but it's probably time for something more cross platform dimensional.

**Comment by lyndsey-ferguson** [comment]
Just a note of clarification, once we are done with our test results, we don't do anything with the junits. They're just a vehicle to get us to where we want to go.

**Comment by jineshqa** [comment]
@fishercraigj do you mind sharing the source code on github? That seems like exactly what I need at the moment, not cross platform but iOS specific. 

Thanks,
JInesh

PS: If you do not wish to share that is fine too just drop a line here so I know :-)
