### ISSUE TITLE
multi_scan using xcpretty?

### ISSUE THREAD

**Issue by nathan-149** [lyndsey-ferguson/fastlane-plugin-test_center#249]
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson. 😍

### Question Subject

Hi, wonderful work! I have been trying to parallelize unit tests! I noticed that multi-scan uses xcpretty under the hood - is this correct? From my understanding, xcpretty doeesn't support parallel output, and xcpretty broke my lane when i saw using an xcodebuild shell command. 

Thanks so much!

**Comment by nathan-149** [comment]
Nevermind, this makes sense to me. it spins up multiple simulators without the built in xcode parallelization, so using xcpretty will work on the separate simulators :)

**Comment by lyndsey-ferguson** [comment]
Yup, it works with `xcpretty`!
