### ISSUE TITLE
Feature Request: disconnect hardware keyboard for the clone simulator when run test in parallel

### ISSUE THREAD

**Issue by reallyyun** [lyndsey-ferguson/fastlane-plugin-test_center#280]
#### Motivation Behind Feature
When the simulator clone connected to the hardware keyboard,  type text might fail due to the keyboard in simulator is not pop up successfully during automation test.  Disconnect the hardware keyboard will solve this problem.  

#### Alternatives or Workarounds
Modified the simulator_helper.rb, added below after row 49 cloned_simulator = simulator.clone
system("defaults write com.apple.iphonesimulator DevicePreferences -dict-add \"#{cloned_simulator.udid}\" \'<dict><key>ConnectHardwareKeyboard</key><false/></dict>\'")

**Comment by ryanpato** [comment]
very interested in this!

**Comment by CorbinMontague** [comment]
+1 to this issue. `scan` launches simulators with the `ConnectHardwareKeyboard` option set to `false` by default, but `multi_scan` seems to have that option set to `true` because my UI tests pass with scan, but fail with `multi_scan` in a way that would only happen if the `ConnectHardwareKeyboard` option was `true`.

**Comment by lyndsey-ferguson** [comment]
I moved this up to the top of the to do list. I am open to PRs, if someone would like to [contribute](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/docs/CONTRIBUTING.md)

**Comment by CorbinMontague** [comment]
I was able to work around this issue just now by executing `defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool false` before the `multi_scan` call. I also added the `reset_simulator` param to the `multi_scan` call set to `true`.

**Comment by lyndsey-ferguson** [comment]
I don't see any code in fastlane's scan that does this, but I only spent 1 minute looking. Once I can properly look at this, I can provide a better, built-in method so that you don't have to _know_ to do this.

**Comment by lyndsey-ferguson** [comment]
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/device_manager.rb#L242

**Comment by lyndsey-ferguson** [comment]
Note to self: this is pending publication for Sponsors.

**Comment by lyndsey-ferguson** [comment]
Released in [Sponsors-first](https://github.com/sponsors/lyndsey-ferguson) version of [v3.15.1](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/docs/feature_details/multi_scan.md). Available to the general public around Dec 18th, 2020!

> Any individual supporter at the Basic Supporter tier or higher will get early access, and all members of an organization sponsor at the Silver tier or higher will get that same access.

**Comment by lyndsey-ferguson** [comment]
Released in [v3.15.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.15.0)
