### ISSUE TITLE
generate report.xcresult for passed tests only. 

### ISSUE THREAD

**Issue by jambudi** [lyndsey-ferguson/fastlane-plugin-test_center#284]
Hello ,

We implemented successfully Fastlane-plugin-test_center. We are trying to integrate with our internal tools and have some question before we modify code ourself. 

Currently, report.xcresult have failures tests and after retry passed tests 

Example Image :

<img width="952" alt="Screen Shot 2020-09-09 at 12 26 51 PM" src="https://user-images.githubusercontent.com/25522050/92565203-e7227500-f297-11ea-94a1-339209df0aa0.png">

How can we share only Passed OR Failed tests? Rather than showing retry logic like tried 2 times and 3rd time it passed.

**Comment by lyndsey-ferguson** [comment]
Are you stating that you are seeing all the failed tests and then the passing tests after the retry? That is a function of the [`xcrun xcresulttool merge`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_xcresults.rb#L22) command; there is not much I can do about that. 

You could also pass `collate_reports: false` to `multi_scan` and choose the xcresult you want.

Or, finally, you could grab the the results of the xcresult yourself with the [`tests_from_xcresult`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/docs/feature_details/tests_from_xcresult.md) action and filter out the duplicates that appear.

**Comment by jambudi** [comment]
@lyndsey-ferguson  Can you provide an example or reference to following suggestion? 

`You could also pass collate_reports: false to multi_scan and choose the xcresult you want.`

**Comment by lyndsey-ferguson** [comment]
What are you looking for? `collate_reports: false` would be an option to `multi_scan` and then you can get the tests that you want from `tests_from_xcresult` by passing in the file paths to the outputted files in the uncollated folders.

**Comment by jambudi** [comment]
Thank you..
