### ISSUE TITLE
Add support for clean parameter on multi_scan

### ISSUE THREAD

**Issue by armando-leal** [lyndsey-ferguson/fastlane-plugin-test_center#30]
Right now if you add clean to the multi_scan action the test will fail because the app binary will be deleted before the tests are actually executed. The error is also very cryptic, so it's hard to know that the issue comes from the *clean* parameter

The clean parameter should either be ignored or used only **once** on the first build and **then ignored** for all subsequent xcodebuild calls.

**Comment by lyndsey-ferguson** [comment]
Thanks for the defect report!

**Comment by lyndsey-ferguson** [comment]
I should have a fix this week

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.0.5](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.0.5)

**Comment by armando-leal** [comment]
Awesome. Thanks for the quick update.
