### ISSUE TITLE
Cert Pinning Error on some simulators

### ISSUE THREAD

**Issue by ssharma0312** [lyndsey-ferguson/fastlane-plugin-test_center#309]
First of all, Thanks for creating this amazing plugin. It is now a must-have thing for our project.

I encountered a very weird issue relating to cert pinning. Recently we have upgraded our XCode to XCode 12.0.1 from 11.4.1, since then we are encountering cert pinning error on some simulators (I would 2-3 simulators out of 6 when tests are running). I have been trying to resolve the issue by experimenting various different option since last 2 weeks but no success.

Has anyone else who is on XCode 12.0.1, where app uses a cert pinning, and have TrustKit (1.6.0) is encountering this issue? Causing my regression test failing.

What I have done so far:
**Attempt 1**:
fastlane-plugin-test_center: 3.14.5
fastlane: 2.161.0
TrustKit: 1.6.0
**Encountered the cert pinning error**

**Attempt 2**:
fastlane-plugin-test_center: 3.11.5
fastlane: 2.155.3
TrustKit: 1.6.0
**Encountered the cert pinning error**
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.162.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-test_center | 3.11.5  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.3.0        |
| slack-notifier              | 2.3.2        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.7.0        |
| terminal-table              | 1.8.0        |
| plist                       | 3.5.0        |
| public_suffix               | 4.0.5        |
| addressable                 | 2.7.0        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| tty-screen                  | 0.8.1        |
| tty-cursor                  | 0.7.1        |
| tty-spinner                 | 0.9.3        |
| babosa                      | 1.0.3        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| excon                       | 0.76.0       |
| faraday                     | 1.0.1        |
| unf_ext                     | 0.0.7.7      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 1.0.0        |
| fastimage                   | 2.2.0        |
| gh_inspector                | 1.1.3        |
| mini_magick                 | 4.10.1       |
| rubyzip                     | 2.3.0        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 1.0.0        |
| dotenv                      | 2.7.6        |
| bundler                     | 1.17.2       |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.8        |
| jwt                         | 2.2.1        |
| uber                        | 0.1.0        |
| declarative                 | 0.0.20       |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| mini_mime                   | 1.0.2        |
| multi_json                  | 1.15.0       |
| signet                      | 0.14.0       |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.38.0       |
| google-cloud-env            | 1.3.3        |
| google-cloud-errors         | 1.0.1        |
| google-cloud-core           | 1.5.0        |
| rake                        | 13.0.1       |
| digest-crc                  | 0.6.1        |
| google-cloud-storage        | 1.27.0       |
| emoji_regex                 | 3.0.0        |
| nanaimo                     | 0.3.0        |
| colored2                    | 3.1.2        |
| claide                      | 1.0.3        |
| CFPropertyList              | 3.0.2        |
| atomos                      | 0.1.3        |
| xcodeproj                   | 1.19.0       |
| json                        | 2.3.1        |
| os                          | 1.1.1        |
| memoist                     | 0.16.2       |
| googleauth                  | 0.13.1       |
| aws-eventstream             | 1.1.0        |
| aws-sigv4                   | 1.2.1        |
| aws-partitions              | 1.353.0      |
| jmespath                    | 1.4.0        |
| aws-sdk-core                | 3.104.3      |
| aws-sdk-kms                 | 1.36.0       |
| aws-sdk-s3                  | 1.76.0       |
| forwardable                 | 1.2.0        |
| logger                      | 1.3.0        |
| stringio                    | 0.0.2        |
| ipaddr                      | 1.2.2        |
| openssl                     | 2.1.2        |
| ostruct                     | 0.1.0        |
| strscan                     | 1.0.0        |
| date                        | 2.0.0        |
| fileutils                   | 1.1.0        |
| etc                         | 1.0.1        |
| io-console                  | 0.4.7        |
| zlib                        | 1.0.0        |
| libxml-ruby                 | 3.1.0        |
| rexml                       | 3.1.9        |
| psych                       | 3.1.0        |
| mutex_m                     | 0.1.0        |
| webrick                     | 1.4.2        |
| xctest_list                 | 1.2.1        |
| colorize                    | 0.8.1        |
| fastlane-plugin-test_center | 3.11.5       |
</details>

**Attempt 3**:
fastlane-plugin-test_center: 3.11.5
fastlane: 2.162.0
TrustKit: 1.6.0
**Encountered the cert pinning error**
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.162.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-test_center | 3.11.5  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.3.0        |
| slack-notifier              | 2.3.2        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.7.0        |
| terminal-table              | 1.8.0        |
| plist                       | 3.5.0        |
| public_suffix               | 4.0.5        |
| addressable                 | 2.7.0        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| tty-screen                  | 0.8.1        |
| tty-cursor                  | 0.7.1        |
| tty-spinner                 | 0.9.3        |
| babosa                      | 1.0.3        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| excon                       | 0.76.0       |
| faraday                     | 1.0.1        |
| unf_ext                     | 0.0.7.7      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 1.0.0        |
| fastimage                   | 2.2.0        |
| gh_inspector                | 1.1.3        |
| mini_magick                 | 4.10.1       |
| rubyzip                     | 2.3.0        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 1.0.0        |
| dotenv                      | 2.7.6        |
| bundler                     | 1.17.2       |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.8        |
| jwt                         | 2.2.1        |
| uber                        | 0.1.0        |
| declarative                 | 0.0.20       |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| mini_mime                   | 1.0.2        |
| multi_json                  | 1.15.0       |
| signet                      | 0.14.0       |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.38.0       |
| google-cloud-env            | 1.3.3        |
| google-cloud-errors         | 1.0.1        |
| google-cloud-core           | 1.5.0        |
| rake                        | 13.0.1       |
| digest-crc                  | 0.6.1        |
| google-cloud-storage        | 1.27.0       |
| emoji_regex                 | 3.0.0        |
| nanaimo                     | 0.3.0        |
| colored2                    | 3.1.2        |
| claide                      | 1.0.3        |
| CFPropertyList              | 3.0.2        |
| atomos                      | 0.1.3        |
| xcodeproj                   | 1.19.0       |
| json                        | 2.3.1        |
| os                          | 1.1.1        |
| memoist                     | 0.16.2       |
| googleauth                  | 0.13.1       |
| aws-eventstream             | 1.1.0        |
| aws-sigv4                   | 1.2.1        |
| aws-partitions              | 1.353.0      |
| jmespath                    | 1.4.0        |
| aws-sdk-core                | 3.104.3      |
| aws-sdk-kms                 | 1.36.0       |
| aws-sdk-s3                  | 1.76.0       |
| forwardable                 | 1.2.0        |
| logger                      | 1.3.0        |
| stringio                    | 0.0.2        |
| ipaddr                      | 1.2.2        |
| openssl                     | 2.1.2        |
| ostruct                     | 0.1.0        |
| strscan                     | 1.0.0        |
| date                        | 2.0.0        |
| fileutils                   | 1.1.0        |
| etc                         | 1.0.1        |
| io-console                  | 0.4.7        |
| zlib                        | 1.0.0        |
| libxml-ruby                 | 3.1.0        |
| rexml                       | 3.1.9        |
| psych                       | 3.1.0        |
| mutex_m                     | 0.1.0        |
| webrick                     | 1.4.2        |
| xctest_list                 | 1.2.1        |
| colorize                    | 0.8.1        |
| fastlane-plugin-test_center | 3.11.5       |
</details>

I have not seen this issue when running using xcodebuild command from terminal i.e. without using fastlane at all --> running more tests to confirm this. 

Currently our GitLab CI/CD is down, I will attach detailed logs (--verbose) in this ticket shortly.

At this point, I trying every option to find the root cause or the version that may have broke it. Any feedback will be appreciated.

**Comment by ssharma0312** [comment]
[multi_scan_verbose_logs.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/5484024/multi_scan_verbose_logs.txt)

Attached --verbose logs

**Comment by ssharma0312** [comment]
After spending quite some time, we found out that issue was related to TrustKit (1.5.3) pod library. After upgrading to TrustKit (1.7.0), and using latest version of Fastlane 2.161.0 this issue is resolved.

**Comment by lyndsey-ferguson** [comment]
Great, thanks for letting me know what the problem was.
