### ISSUE TITLE
Update example for tests_from_xctestrun

### ISSUE THREAD

**Issue by Cyberbeni** [lyndsey-ferguson/fastlane-plugin-test_center#311]
### Feature Request
Update example for tests_from_xctestrun

#### Motivation Behind Feature

The current example doesn't demonstrate any real life use case, just prints the test names. I think the most common use case for this action is to build the tests on 1 CI machine, split the test cases into multiple parts and then run those tests on multiple CI machines parallelly.

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson. 😍

#### Feature Description

We currently use this lane to generate the test batches that will be run on different machines:
```ruby
  lane :split_tests do |options|
    tests = tests_from_xctestrun(xctestrun: options[:xctestrun_path]).values.flatten.shuffle
    slice_size = (tests.size/options[:split].to_f).ceil
    tests.each_slice(slice_size).each_with_index { |innerArray, index|
      File.write("#{options[:out_path]}/batch#{index}.txt", innerArray.join(','))
    }
  end
```
and then we read the file and pass the contents to multi_scan:
```ruby
  lane :run_built_tests_with_matching_name do |options|
    multi_scan(
      ...
      only_testing: options[:test_name].split(','),
    )
  end
```

**Comment by Cyberbeni** [comment]
(Jenkins has a bug where rerunning a job can result a multiline string turning into single line, making separating with "," better than "\n", so only testing a couple tests without splitting can use the same lane)

**Comment by lyndsey-ferguson** [comment]
Done!
