### ISSUE TITLE
Fix TestsFromXcresultAction tests identifiers

### ISSUE THREAD

**Issue by yakimant** [lyndsey-ferguson/fastlane-plugin-test_center#321]
Currently tests are reported as `TestSuite/TestSuite/TestName()`, but should as `TestTarget/TestSuite/TestName()`

See also https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/292

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.15.2](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.15.2)
