### ISSUE TITLE
multi_scan overwriting code coverage reports between runs

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#33]
When `multi_scan` completes a test run with failing tests, and starts another run of just the failing tests, it deletes the code coverage reports. When the `multi_scan` action completes, the code coverage reports are incomplete and misleading.

While the action could simply give the user options to use `slather` to create HTML, XML, etc. files and then merge those, it would be better if the algorithms to convert the reports could be used to figure out what needs to be safeguarded and then consolidate that data into one set of reports that can be used directly or converted en masse with tools such as `slather`.

See Issue #31

**Comment by lyndsey-ferguson** [comment]
Can you, @zacoid55 @gmgchow @kisialiu @kaybutter @NXGieng @armando-leal @fishercraigj @dionc , give me a thumbs up on a ticket which you think should be worked on next? I want to make sure that my priorities will provide you the best impact.

**Comment by zacoid55** [comment]
Sure thing!

**Comment by NXGieng** [comment]
Hi @lyndsey-ferguson , sorry for the delay reply, yeah, sure I will. 
I'm still looking for a way to correct the test coverage, so please let me know if you found out.
Thanks

**Comment by lyndsey-ferguson** [comment]
It seems that the code coverage report is in derived data, a file named `*.xccoverage`

**Comment by lyndsey-ferguson** [comment]
`slather` will read it and convert it to an xml file.

**Comment by lyndsey-ferguson** [comment]
It may be tricky to handle batches and turning off code coverage after the first run as then we will lose code coverage reports for other batches.

**Comment by lyndsey-ferguson** [comment]
Maybe the the [xcov tool](https://github.com/nakiostudio/xcov) can help

**Comment by lyndsey-ferguson** [comment]
It looks like [xcov-core](https://github.com/nakiostudio/xcov-core) can help me understand how to parse the file. It seems that it is an NSArchived file of NSObjects. I can use the code to read the file into a NSDictionary, figure out how to collate it, and then NSArchive it out.

**Comment by lyndsey-ferguson** [comment]
Probably the next best step is to export each HTML or JSON file to a separate numbered file and then compare the files to see how I can merge the files.

**Comment by lyndsey-ferguson** [comment]
It looks like the subsequent code coverage report could be just a subset of the first code coverage report: I will simply keep the first report and turn off code-coverage after the first run. My only concern is with batching...

I will have to add the batch number to each `xccoverage` file and see if `slather` can handle that.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.5.3](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.5.3)

**Comment by lyndsey-ferguson** [comment]
Each batch creates a new unique `xccoverage` file. `slather` can read multiple `xccoverage` files to create multiple xml files.

**Comment by Haibo-Zhou** [comment]
@lyndsey-ferguson May I know if this bug has been fixed now. I meet the same issue with Xcode 13 when doing multi-Scan for my UITest. The coverage report will take the last scan as its output, since the last scan only cares a few failed test cases normally, then the coverage would be much lower than the actual result.

**Comment by Haibo-Zhou** [comment]
@lyndsey-ferguson I found the same issue on 3.15.3 (the latest version). The coverage report will take the last scan result as its input, since the last scan only cares a few failed test cases normally, then the coverage would be much lower than the actual result.
