### ISSUE TITLE
Question: Why Scanfile overrides multi_scan options

### ISSUE THREAD

**Issue by AyaAkl25** [lyndsey-ferguson/fastlane-plugin-test_center#340]
### New Issue Checklist

- [ yes] Updated `fastlane-plugin-test_center` to the latest version
- [ yes] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [ yes] I reviewed the example [Fastfile](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/fastlane/Fastfile)
- [ ] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
When having options inside multi_scan like `scheme` or `workspace` but there is already these options as default in scanfile, I can see that multi_scan overrides its option with options of scanfile. Although I checked this is not happening with normal run_tests action of fastlane. 
I also checked the code and logs displayed and I find a line of log that shows that this overrides is intended to happen, but was wondering why? because in some cases I don't want multi_scan to take the options from scanfile
So my question like I mentioned in issue above, why is this intended and how could I change that if possible? 

Thank you for such great tool, We use it now to work with parallel execution and retry logic which is helping us a lot.

**Comment by lyndsey-ferguson** [comment]
Hello @AyaAkl25 , I have moved this question to a Discussion question: https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/discussions/342
