### ISSUE TITLE
NoMethodError: [!] undefined method error

### ISSUE THREAD

**Issue by ssharma0312** [lyndsey-ferguson/fastlane-plugin-test_center#347]
Batch .xcresult files are not merging to produce 1 final report, and pipeline failing with error `NoMethodError: [!] undefined method `value' for nil:NilClass`

Fastlane version: 2.187.0
Fastlane-plugin-test_center: 3.15.3

Test are called in gitlab pipelines like following:
`bundle exec fastlane ios scanUITest scheme:XXX branch:master`

Fastfile
`# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncoomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Full UI Scan"
  lane :scanUITest do |options|
    sh "rm -rf test_output/#{options[:branch]}/*"

    test_run_block = lambda do |testrun_info|
      failed_test_count = testrun_info[:failed].size
      passed_test_count = testrun_info[:passing].size
      try_attempt = testrun_info[:try_count]
      batch = testrun_info[:batch]

      UI.message("Current Failed count #{failed_test_count}")
      UI.message("Current Passed count #{passed_test_count}")

      if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')
        if try_attempt < 3
          UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
        end
      end

      UI.message("Everything is fine, let's continue try #{try_attempt + 1} for batch #{batch}")
    end

    # disable_simulators_keyboard
    multi_scan(
      workspace: "XXX.xcworkspace",
      scheme: options[:scheme],
      output_types: 'junit,html',
      output_files: "junit.xml,report.html",
      try_count: 3, # retry _failing_ tests up to three times^1.
      batch_count: 5,
      code_coverage: true,
      parallel_testrun_count: 5, # run subsets of your tests on parallel simulators^2
      testrun_completed_block: test_run_block,
      devices: "iPhone 11",
      result_bundle: "TestResults", # To generate test reports
      output_directory: "./fastlane/test_output/" + options[:branch]
    )

  end
end
`

fastlane env
`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H524)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncoomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :preprod do
    get_certificates(
      username: "boh@atb.com",
      generate_apple_certs: false
    )
    get_provisioning_profile(
      adhoc: true,
      username: "boh@atb.com",
      app_identifier: "com.atb.rebank"
    )
    build_app(
      scheme: "RebankPreProd",
      workspace: "Rebank.xcworkspace",
      silent: true,
      clean: true,
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "Rebank"
    )
  end

  lane :prod do
    get_certificates(
      username: "boh@atb.com",
      generate_apple_certs: false
    )
    get_provisioning_profile(
      username: "boh@atb.com",
      app_identifier: "com.atb.rebank"
    )
    build_app(
      scheme: "RebankProd",
      workspace: "Rebank.xcworkspace",
      silent: true,
      clean: true,
      output_directory: "./build",
      output_name: "Rebank",
      export_options: {
        provisioningProfiles: {
          "com.atb.rebank" => "Rebank App Store"
        }
      }
    )
  end

  desc "Disable Hardware Keyboard Off"
  lane :disable_simulators_keyboard do
    sh "bash ./disable_simulators_keyboards.sh"
  end

  desc "Coverage Report"
  lane :coverage do
    xcov(
      workspace: "Rebank.xcworkspace",
      scheme: "RebankPreProdTest",
      output_directory: "fastlane/coverage_output",
      only_project_targets: true,
      ignore_file_path: "fastlane"
    )
  end

  desc "Full UI Scan"
  lane :scanUITest do |options|
    sh "rm -rf test_output/#{options[:branch]}/*"

    test_run_block = lambda do |testrun_info|
      failed_test_count = testrun_info[:failed].size
      passed_test_count = testrun_info[:passing].size
      try_attempt = testrun_info[:try_count]
      batch = testrun_info[:batch]

      UI.message("Current Failed count #{failed_test_count}")
      UI.message("Current Passed count #{passed_test_count}")

      if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')
        if try_attempt < 3
          UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
        end
      end

      UI.message("Everything is fine, let's continue try #{try_attempt + 1} for batch #{batch}")
    end

    # disable_simulators_keyboard
    multi_scan(
      workspace: "Rebank.xcworkspace",
      scheme: options[:scheme],
      output_types: 'junit,html',
      output_files: "junit.xml,report.html",
      try_count: 3, # retry _failing_ tests up to three times^1.
      batch_count: 5,
      code_coverage: true,
      parallel_testrun_count: 5, # run subsets of your tests on parallel simulators^2
      testrun_completed_block: test_run_block,
      devices: "iPhone 11",
      result_bundle: "TestResults", # To generate test reports
      output_directory: "./fastlane/test_output/" + options[:branch]
    )

  end

  desc "Full UI Scan for Coverage"
  lane :scanUITestForCoverage do
    # disable_simulators_keyboard
    scan(
      workspace: "Rebank.xcworkspace",
      devices: ["iPhone 11"],
      scheme: "RebankPreProdTest",
      code_coverage: true,
      disable_concurrent_testing: true,
      xcargs: "-parallel-testing-enabled NO",
      output_types: 'junit',
      output_files: "junit.xml"
    )
  end

  desc "Dev Mock test"
  lane :testDevMockTest do
    run_tests(workspace: "Rebank.xcworkspace",
      devices: ["iPhone 11"],
      scheme: "RebankPreProd"
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.15.3  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.8        |
| retriable                       | 3.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.20.0       |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| babosa                          | 1.0.4        |
| excon                           | 0.84.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.4        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.5.1        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.4        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| jwt                             | 2.2.3        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| mini_mime                       | 1.1.0        |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| webrick                         | 1.7.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.3        |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-partitions                  | 1.478.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.117.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| trainer                         | 0.9.1        |
| xctest_list                     | 1.2.1        |
| colorize                        | 0.8.1        |
| fastlane-plugin-test_center     | 3.15.3       |
</details>

*generated on:* **2021-07-19**
</details>`

**Comment by lyndsey-ferguson** [comment]
@ssharma0312 can you include the logs? I'd like to see the stack trace.

**Comment by ssharma0312** [comment]
My suspect is that it could be related to following error, as I seen this issue only when one of the test fails due to 

`XXX.app encountered an error (Failed to prepare device 'iPhone 11 Clone 2 TestCenter::Helper::MultiScanManager::SimulatorHelper<70251400702060>' for impending launch. If you believe this error represents a bug, please attach the result bundle at /Users/rebankbuildmachine/builds/FAypYkBb/0/atbdigitalteam/enes/rebank/atb-rebank-ios/fastlane/test_output/fastlaneBugVerbose/XXXTests-batch-2/report.xcresult. (Underlying Error: Unable to boot the Simulator. launchd failed to respond. (Underlying Error: Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding)))`

Also attached completed logs for the pipeline executed with verbose flag.
[verboseLogs.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/6843645/verboseLogs.txt)

**Comment by ssharma0312** [comment]
XCode version 12.4

**Comment by ssharma0312** [comment]
Upon further investigation, I found this failed due to fastlane using ruby 2.6.3, after setting ruby version to 2.7.2 this issue seems to be resolved.

**Comment by lyndsey-ferguson** [comment]
That makes sense. It didn't look like an error with the collation per-se, but rather a missing device.
