### ISSUE TITLE
Allow to pass test plans instead of running all tests into a scheme

### ISSUE THREAD

**Issue by dennismozart1994** [lyndsey-ferguson/fastlane-plugin-test_center#354]
### Feature Request
Currently there's no support for all scan features into multiscan and lots of pretty useful features are out of support right now, like concurrent_workers and mainly test_plan options.
The testplan option allows us to pass a set of tests through an Xcode file instead of having to use multiple schemes for different sets of tests like Smoke, Regression, etc... This allow us to have a solid and organized testing suite inside the project and only run/edit the testplan whenever we need to.

#### Motivation Behind Feature
It's a lot easier to work with testplans than specifying all tests through only_testing option and their driving/creating new features for it as Xcode evolves.

#### Feature Description
Allow the possibility of specifying a testplan to run on multi_scan as is on scan as described at https://docs.fastlane.tools/actions/scan/

#### Alternatives or Workarounds
Currently the only way of specifying sets of tests is by using only_testing with multi_scan, which is a bit anoying, since it scans and runs all tests into the scheme, ruining different sets of testplans in a well organized project according to Xcode new standards.

**Comment by dennismozart1994** [comment]
nvm

**Comment by lyndsey-ferguson** [comment]
@dennismozart1994 did you see that multi_scan runs on scan and you can pass in scan params? I just want to make sure that you saw that 😄
