### ISSUE TITLE
Multi-scan using a deprecated option

### ISSUE THREAD

**Issue by tejassharma96** [lyndsey-ferguson/fastlane-plugin-test_center#357]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see
- [x] I have reviewed the [Discussions forum](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/discussions) to see my question has already been addressed.

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson. 😍
>

### Issue Description

Using multi_scan, I get the following warning:
```
Warning: -disable-concurrent-testing is deprecated. Use -disable-concurrent-destination-testing instead.
```

Just wanted to bring it to attention so the plugin can switch to the non-deprecated version after making any needed changes earlier rather than later.

**Comment by lyndsey-ferguson** [comment]
Hello @tejassharma96, can you tell me which version of Xcode you're using? Also, I don't think my plugin specifically uses that flag...have you created an Issue with fastlane's scan tool (multi_scan uses scan under the hood)?

https://github.com/fastlane/fastlane/commit/a4f5daa5fdafb9bb03204b9c204f7c1e76d4c654#diff-e99d2d02f1b755b1df79d1659c11eb0ce5a2f3d3c77995350dba3a771a29e33eR41

**Comment by tejassharma96** [comment]
I'm using 12.5.1, I'll go ahead and create an issue in the fastlane space.
