### ISSUE TITLE
"Failed to prepare device" error is not retried and causes crash when collating the reports

### ISSUE THREAD

**Issue by Cyberbeni** [lyndsey-ferguson/fastlane-plugin-test_center#366]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see
- [x] I have reviewed the [Discussions forum](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/discussions) to see my question has already been addressed.

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson. 😍
>

### Issue Description

Occasionally one of the batches result in the following error:
> Assertions: System: Failed to prepare device 'iPhone 12 jawxo Clone 6 TestCenter::Helper::MultiScanManager::SimulatorHelper<5240>' for impending launch. If you believe this error represents a bug, please attach the result bundle at /***/TestResult/MyAppTests-batch-6/report.xcresult. (Underlying Error: Unable to boot the Simulator. launchd failed to respond. (Underlying Error: Failed to start launchd_sim: could not bind to session, launchd_sim may have crashed or quit responding))

This will result in the following result.xml:
[result.xml.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/7641557/result.xml.txt)

This error won't be retried and when collating the results, we get the following crash:
```
collate_junit_reports.rb:13:in `block in run': [!] undefined method `value' for nil:NilClass (NoMethodError)
```

**Comment by Cyberbeni** [comment]
For some reason we were not passing true to retry_test_runner_failures even though I was the one who added that.

**Comment by lyndsey-ferguson** [comment]
I want to apologize that I have not responded to this issue. A family health issue is requiring me to narrow my focus on the essentials and I don't have the time I need to focus on the plugin more than a minute. If you can get some other contributors to this project to help with this, I would consider merging a resulting PR.

**Comment by Cyberbeni** [comment]
Haven't seen this error in a while.

**Comment by lyndsey-ferguson** [comment]
I'll close it for now.
