### ISSUE TITLE
Multi_scan generate coverage reports base on last scan.

### ISSUE THREAD

**Issue by Haibo-Zhou** [lyndsey-ferguson/fastlane-plugin-test_center#367]
I found this same issue which has fixed in #33, but I meet this issue today in the latest version (3.15.3) when performing iOS UITest in Xcode 13 with fastlane. For instance, I run 10 test cases with 1 failure, and the 2nd scan re-run this failure case and with passed result. The final test coverage would be take in account with the 2nd scan result, which is much lower than the actual coverage. So multi-run doesn't merge all its scan into one coverage report.

Below is the code in `Fastfile`, is there anything I am missing?

```
desc "Build and Run Test Cases"
lane :tests do
  Dir.chdir("..") do
    enable_simulators_keyboard
    clear_xcov_output
    clear_derived_data
    sh("xcodebuild","-resolvePackageDependencies")
  end
    
    multi_scan(
      project: 'xxx.xcodeproj',
      scheme: 'xxx',
      try_count: 3, # retry _failing_ tests up to three times
      fail_build: false,
      parallel_testrun_count: 1, # run subsets of your tests on parallel simulators
      device: "iPhone 13",
      testrun_completed_block: test_run_block
    )
  test_xcov
end

desc "Generate UITest Coverage Report"
lane :test_xcov do
xcov(
  project: "xxx.xcodeproj",
  scheme: "xxx",
  output_directory: "./fastlane/xcov_output",
  minimum_coverage_percentage: 80.0
)
end

```

**Comment by daianaiziatovTradeRev** [comment]
+
Faced the same issue, although I manually collate `xcresults` from every batch with `collate_xcresults`.

**Comment by lyndsey-ferguson** [comment]
I want to apologize that I have not responded to this issue. A family health issue is requiring me to narrow my focus on the essentials and I don't have the time I need to focus on the plugin more than a minute. If you can get some other contributors to this project to help with this, I would consider merging a resulting PR.

**Comment by cah-suraj-bangera** [comment]
> ✚
> Faced the same issue, although I manually collate `xcresults` from every batch with `collate_xcresults`.

@daianaiziatovTradeRev Can you please attach script for how you are performing this? Sounds like this could help me in the issue I am facing

**Comment by daianaiziatovTradeRev** [comment]
> > ✚
> > Faced the same issue, although I manually collate `xcresults` from every batch with `collate_xcresults`.
> 
> @daianaiziatovTradeRev Can you please attach script for how you are performing this? Sounds like this could help me in the issue I am facing

Sure, this is what we did:
```ruby
lane :uitest do
    reset_simulator_contents
    clear_derived_data(derived_data_path: ENV["DERIVED_DATA_UITEST"])
    sh "rm -Rf logs"

    collate_reports_lambda = lambda {
      xcresults = Dir['../fastlane/logs/batches-reports/**/*.xcresult'].map { |relpath| File.absolute_path(relpath) }
      Dir.chdir("..") do
        collate_xcresults(
          xcresults: xcresults,
          collated_xcresult: Dir.pwd + "/fastlane/logs/result.xcresult"
        )
      end
    }
    begin
      multi_scan(
        scheme: "AppQAScheme",
        clean: true,
        device: "iPhone 8",
        include_simulator_logs: false,
        buildlog_path: 'fastlane/logs/build',
        skip_slack: true,
        output_directory: "fastlane/logs/batches-reports/",
        parallel_testrun_count: 3,
        batch_count: 3,
        output_types: "xcresult",
        output_files: "result.xcresult",
        retry_test_runner_failures: true,
        try_count: 3,
        derived_data_path: ENV["DERIVED_DATA_UITEST"],
        code_coverage: true,
        collate_reports: false
      )
      collate_reports_lambda.call # <- this what makes the trick
    rescue Exception => exceptionrescue
      collate_reports_lambda.call
      raise exceptionrescue
    end
    sh "mkdir -p sonar-reports"
    sh "sh xccov-to-sonarqube-generic.sh logs/result.xcresult > sonar-reports/sonarqube-generic-coverage.xml"
  end
```
It is still not 100% accurate in terms of coverage tho
We also just moved from this framework recently to Xcode 13 retry.

**Comment by lyndsey-ferguson** [comment]
Can someone in this thread please include a sample project that I can use to reproduce this issue? Thanks!

**Comment by lyndsey-ferguson** [comment]
Closing this issue as I need a sample project to reproduce this quickly.
