### ISSUE TITLE
for xcode13 testPlan retryOnFailure

### ISSUE THREAD

**Issue by beiliubei** [lyndsey-ferguson/fastlane-plugin-test_center#368]
![image](https://user-images.githubusercontent.com/1127875/145368185-c9fe51c5-b3a9-4859-8f5a-156ec87fbe1d.png)

the report should mark it as passed

**Comment by lyndsey-ferguson** [comment]
I want to apologize that I have not responded to this issue. A family health issue is requiring me to narrow my focus on the essentials and I don't have the time I need to focus on the plugin more than a minute. If you can get some other contributors to this project to help with this, I would consider merging a resulting PR.

**Comment by lyndsey-ferguson** [comment]
@beiliubei can you please submit a sample project that exhibits this issue so I can reproduce and fix it? Thanks

**Comment by lyndsey-ferguson** [comment]
Closing the issue as I have no sample to reproduce the issue.
