### ISSUE TITLE
XCTestHTMLReport(Index.html) is empty and doesn't show any test results

### ISSUE THREAD

**Issue by appajit** [lyndsey-ferguson/fastlane-plugin-test_center#373]
The `report.html` shows up all test results but the `index.html` doesn't show any results. It would be great if you could help us to resolve this issue. Here is our configuration:

```
 multi_scan(
        workspace: '../../ios/xxxxxx.xcworkspace',
        scheme: ENV['XCUI_SCHEME'],
        try_count: 3, # retry _failing_ tests up to three times^1.
        parallel_testrun_count: 1,
        fail_build: false,
        derived_data_path: ENV['DERIVED_DATA_DIRECTORY'],
        devices: ["iPhone 11"],
        buildlog_path: ENV['XCUITEST_OUTPUT_DIRECTORY'],
        result_bundle: true,
        skip_build: true,
        output_directory: ENV['XCUITEST_OUTPUT_DIRECTORY'],
        should_zip_build_products: true,
        include_simulator_logs: true
      )
```

**Comment by lyndsey-ferguson** [comment]
I want to apologize that I have not responded to this issue. A family health issue is requiring me to narrow my focus on the essentials and I don't have the time I need to focus on the plugin more than a minute. If you can get some other contributors to this project to help with this, I would consider merging a resulting PR.

**Comment by lyndsey-ferguson** [comment]
@appajit can you provide a sample project that exhibits this problem so that I can debug and fix the issue? Thanks!

**Comment by lyndsey-ferguson** [comment]
Closing the issue as I have no sample to reproduce the issue.
