### ISSUE TITLE
Suppress actions do not use xcworkspace files

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#4]
My intent was to use the xcworkspace file to find out which tests are suppressed or suppress tests for projects automatically. The actions do not currently support that.

**Comment by zacoid55** [comment]
@lyndsey-ferguson don't suppose you managed to make any head way on this at all? :D

**Comment by lyndsey-ferguson** [comment]
😄 I am working on a big feature for this plugin. As you spoke up about this (I think this is the second time someone's mentioned this), I will prioritize this as the next item after the feature. Thanks for your interest!

**Comment by zacoid55** [comment]
Thank you for the speedy answer! I'm excited to see this feature

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.3.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v3.3.0)
