### ISSUE TITLE
using batch flag does not aggregate the HTML reports into single report

### ISSUE THREAD

**Issue by Sandhu412** [lyndsey-ferguson/fastlane-plugin-test_center#42]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the example [Fastfile](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/fastlane/Fastfile)

### Issue Description

If we use batch_count flag, then after the tests are run, multiple HTML reports are generated. 
For ex: if batch_count is set to 3, then there will be 3 HTML reports for the 3 test runs: report.html, report-2.html and report-3.html

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
@Sandhu412 to let you know, I am open to pull requests. You can take a look at the [`collate_junit_reports`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb) action for an example of how to parse XML/HTML files.

**Comment by lyndsey-ferguson** [comment]
This has been added in [v3.2.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.2.0)

**Comment by Sandhu412** [comment]
@lyndsey-ferguson -- Thanks for making this feature available. But could you please point me to an example of how to use this action? The example Fastfile in the README does not have an action using collate_html_reports. Appreciate it thanks!

**Comment by lyndsey-ferguson** [comment]
@Sandhu412 good catch. I don't have a _great_ example, but try this:

```ruby
report_files = Dir.glob("#{output_directory}/*.html").map do |relative_filepath|
  File.absolute_path(relative_filepath)
end

if report_files.size > 1
  collate_html_reports(
    # sort the files so that the oldest is listed first in the list of files
    reports: report_files.sort { |f1, f2| File.mtime(f1) <=> File.mtime(f2) },
    collated_report: File.absolute_path(File.join(output_directory, 'report.html'))
  )
end
```

**Comment by lyndsey-ferguson** [comment]
I created an [Issue](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/46) for this.

**Comment by Sandhu412** [comment]
Thanks. Sure, will try that snippet of code.

**Comment by Sandhu412** [comment]
@lyndsey-ferguson -- I tried the snipper of code you provided and I see that its collating the reports and generating one report.html file but the file is empty. Below is the updated lane with the code. Since batch_count is 4, it is generating 5 reports in total as per the logs but the report itself is empty. Any thoughts? 

desc "Runs all the TK UI Tests"
  lane :toolkit_ui_tests do
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '120'
    clear_derived_data
    sh('mkdir -p ../reports/uitest-coverage/')
    sh('mkdir -p ../reports/uitest-xcov-coverage/')
    output_directory = "reports/ui-tests"
    cocoapods(repo_update: false, silent: true) # CP repo update moved to a Jenkins task that runs once a day
    multi_scan(
      workspace: File.absolute_path('../Toolkit.xcworkspace'),
      device: "iPhone 8",
      scheme: 'ToolkitUITests',
      output_directory: "reports/ui-tests",
      include_simulator_logs: false,
      try_count: 2, # runs only the failed tests again without building to the set count
      batch_count: 4, # batches the total number of tests into set count to reduce the load on simulator
      fail_build: true,
      code_coverage: true
    )
    report_files = Dir.glob("#{output_directory}/*.html").map do |relative_filepath|
    File.absolute_path(relative_filepath)
    end
    if report_files.size > 1
      collate_html_reports(
        # sort the files so that the oldest is listed first in the list of files
        reports: report_files.sort { |f1, f2| File.mtime(f1) <=> File.mtime(f2) },
        collated_report: File.absolute_path(File.join(output_directory, 'report.html'))
    )
    end

**Comment by lyndsey-ferguson** [comment]
Can you add this _before_ you call `multi_scan`:
```ruby
test_run_block = lambda do |info|
  puts info[:report_files]
end
```

and this inside your call to `multi_scan`:
`testrun_completed_block: test_run_block`?

**Comment by lyndsey-ferguson** [comment]
Can you run this and include the output from the Terminal?

**Comment by lyndsey-ferguson** [comment]
@Sandhu412 I think that there a miscommunication. Let me share my thoughts:

1. I want to see the output from your current lane that you have:

![lane](https://user-images.githubusercontent.com/13001679/39277833-d61d4f40-48bd-11e8-8891-c5cd6a7fa55b.png)

2. I do not see the summary that `multi_scan` prints out at the very beginning. Can you attach the entire log?

3. The `multi_scan` summary also seems to indicate that only 6 tests were run, and there were no failures, thus there should be only one report to "collate".

```ruby
+-------------------+---------------------------------------------------------------------------+
| multi_scan results |
+-------------------+---------------------------------------------------------------------------+
| result | true |
| total_tests | 6 |
| passing_testcount | 6 |
| failed_testcount | 0 |
| failed_tests | [] |
| total_retry_count | 0 |
| report_files | ["/Users/sanjaneya/Documents/toolkit-ios/reports/ui-tests/report.junit", |
| | "/Users/sanjaneya/Documents/toolkit-ios/reports/ui-tests/report.html"] |
+-------------------+---------------------------------------------------------------------------+

```

4. I do see **multiple** runs of `scan` but only 1 run is actually running tests. Do you have code in your test-targets that have methods with names starting with `test`? 

If so, that will break the programmatic method of finding the tests unfortunately. 

That does not yet explain to me why there the resultant html file is empty. That leads me to my next request.

5. Change this:

```ruby
test_run_block = lambda do |info|
  puts info[:report_files]
end
```

to this:

```ruby
test_run_block = lambda do |info|
  info[:report_files].each do |filepath|
    puts '-'*80
    puts File.open(filepath).read
  end
  puts '-'*80
end
```

That will print out the report files to the console.

Once you update your lane, re-run the lane and include **all** of the log printed to the console

My theory is that batching of the tests is not _updating_ the report files and that `scan` is overwriting the report file each time.

**Comment by lyndsey-ferguson** [comment]
> Below is the complete output from the lane after replacing the new code snippet you provided. (I skipped all the build portion of the app since its not relevant). multi_scan lane fails with the error "ERROR [2018-04-29 22:13:30.65]: undefined method `each' for nil:NilClass" . Should I add anything for ".each" call to work?

I provided you the wrong code.  Update the `test_run_block` to be:

```ruby
test_run_block = lambda do |info|
  if info[:report_filepath]
    puts '-'*80
    puts File.open(info[:report_filepath]).read
  else
    puts 'no report_filepath found in info!'
  end
  puts '-'*80
end
```

> Also, I didn't understand what you meant by one of your questions (given below):
"I do see multiple runs of scan but only 1 run is actually running tests. Do you have code in your test-targets that have methods with names starting with test? If so, that will break the programmatic method of finding the tests unfortunately."
>
> -- having methods with name starting with "test" is a apple requirement for writing XCUI tests, isnt it?

Do you see the multiple instances of this in your logs?

```
+--------------------+---+
| Test Results |
+--------------------+---+
| Number of tests | 0 |
| Number of failures | 0 |
+--------------------+---+
```

That means that no tests ran for those "batches". It seems that you have methods that have their name starting with 'test' and that is being picked up as a test. For example, this block of the console indicates that a list of methods are being sent to `xcodebuild` to "only" test and the result is that no *true* tests were run as evidenced by the 0 tests/0 failures result.

```
-only-testing:ToolkitUITests/ContactDetailsTests/testViewContactDetails -only-testing:ToolkitUITests/ContactDetailsTests/testVerifyModifyingEmailLists -only-testing:ToolkitUITests/ContactDetailsTests/testVerifyAtleastOneEmailListError -only-testing:ToolkitUITests/DraftDashboardTests/testViewDraftCampaignDetails -only-testing:ToolkitUITests/SearchContactsTests/testVerifyZeroSearchResults -only-testing:ToolkitUITests/SearchContactsTests/testVerifySortInContactsSearch -only-testing:ToolkitUITests/SearchContactsTests/testViewContactDetailsInContactsSearch -only-testing:ToolkitUITests/SearchContactsTests/testTapSearch -only-testing:ToolkitUITests/ScheduleDashboardTests/testScheduleDashboard -only-testing:ToolkitUITests/ScheduledCampaignTests/testScheduleDraftCampaign -only-testing:ToolkitUITests/ScheduledCampaignTests/testScheduleNoSendToListError -only-testing:ToolkitUITests/ContactsAcceptanceTests/testContactsUserScenario1 -only-testing:ToolkitUITests/ContactsAcceptanceTests/testContactsUserScenario2 -only-testing:ToolkitUITests/ContactsAcceptanceTests/testContactsUserScenario3 -only-testing:ToolkitUITests/ContactsAcceptanceTests/testContactsUserScenario4
```

**Comment by lyndsey-ferguson** [comment]
@Sandhu412 I have created a new issue #49. Let's continue our discussion there.
