### ISSUE TITLE
multi_scan fails to retry failed tests

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#6]
### Description

The `multi_scan` action fails to retry failed tests.

### Details

After a `scan` results in one or more failed tests, `multi_scan` does try to re-run the tests with the failed tests. However, because it does not provide the 'testable' portion of the test identifier, no tests are run.

For example, `multi_scan` provides this `scan` option: `only_testing: ["AtomicBoyUITests/testExample2"]`. The correct identifier to pass is `AtomicBoyUITests/AtomicBoyUITests/testExample2`.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v2.0.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/v2.0.0)

**Comment by zacoid55** [comment]
Thanks so much for this, @lyndsey-ferguson - works like a charm
