### ISSUE TITLE
multi_scan's use of tests_from_xctestrun action not able to find xctest binary

### ISSUE THREAD

**Issue by homebizjunk** [lyndsey-ferguson/fastlane-plugin-test_center#63]
I executed the following lane. Just when it is about to start the test, I got the following error and saying /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:27:in `binary_path': [!] Missing xctest binary:' Please help me out in resolving this issue. Thank you in advance!

fastlane buildBVT

[14:10:22]: ▸ Test build Succeeded
+--------------------+---+
| Test Results |
+--------------------+---+
| Number of tests | 0 |
| Number of failures | 0 |
+--------------------+---+

+----------------------------+----------------+
| Lane Context |
+----------------------------+----------------+
| DEFAULT_PLATFORM | mac |
| PLATFORM_NAME | mac |
| LANE_NAME | mac buildBVT |
| SCAN_DERIVED_DATA_PATH | ../DerivedData |
| SCAN_GENERATED_PLIST_FILES | [] |
| SCAN_GENERATED_PLIST_FILE | |
+----------------------------+----------------+

+------+------------------+-------------+
| fastlane summary |
+------+------------------+-------------+
| Step | Action | Time (in s) |
+------+------------------+-------------+
| 1 | opt_out_usage | 0 |
| 2 | default_platform | 0 |
| 💥 | multi_scan | 37 |
+------+------------------+-------------+

[14:10:22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run fastlane env to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:27:in binary_path': [!] Missing xctest binary: '../DerivedData/Build/Products/Release/...DesktopUITests-Runner.app/Contents/PlugIns/...DesktopUITests.xctest/...DesktopUITests' (RuntimeError) from /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:36:inobjc_tests'
from /Library/Ruby/Gems/2.3.0/gems/xctest_list-1.1.3/lib/xctest_list.rb:68:in tests' from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:15:inblock in xctestrun_tests'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:14:in each' from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:14:inxctestrun_tests'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb:7:in run' from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:58:intestables_tests'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:54:in scan_testable' from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:41:inblock in scan'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:40:in each' from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:40:inscan'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-test_center-3.5.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:23:in run' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:inblock (2 levels) in execute_action'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in execute_action' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:inblock in execute_action'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in chdir' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:inexecute_action'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in trigger_action_by_name' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:inmethod_missing'
from Fastfile:327:in block (2 levels) in parsing_binding' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:incall'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in block in execute' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:inchdir'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in execute' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:incruise_lane'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in handle' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:inblock (2 levels) in run'
from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in call' from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:inrun'
from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in run_active_command' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:inrun!'
from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in run!' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:inrun'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in start' from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:intake_off'
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in <top (required)>' from /usr/local/bin/fastlane:22:inload'
from /usr/local/bin/fastlane:22:in `

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.5                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.2 (Apple Git-101.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.5 (17F70a)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.4.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
#update_fastlane
# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "1.105.1"
opt_out_usage

default_platform :mac

platform :mac do
before_all do
# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
end

desc "Execute BVT Tests"
lane :bvt do
scan(
workspace:"../CitrixFiles.xcworkspace",
scheme:"SFMDriveMapperBVT",
configuration:"Release",
code_coverage: true,
derived_data_path: "../DerivedData",
output_types: "html,junit,json-compilation-database",
output_directory: "../build/reports/UI_test",
buildlog_path: "../build/logs/xcodebuild"
)
end


desc "Build ShareFile Drive Mapper Project and run BVT test"
lane :buildBVT do |options|
    scheme_to_test = "SFMDriveMapperBVT"
    multi_scan(
        workspace:"../CitrixFiles.xcworkspace",
        scheme: scheme_to_test,
        configuration:"Release",
        code_coverage: true,
        derived_data_path: "../DerivedData",
        output_types: "html,junit,json-compilation-database",
        output_directory: "../build/reports/UI_test",
        try_count: 6,
        buildlog_path: "../build/logs/xcodebuild"
    )
end

# Rename JUnit report file to match standard (required for SonarQube analysis)
  # sh "cd ../build/reports/UI_test && mv cobertura.xml results/SFDesktopTestCoverage.xml "
end


# You can define as many lanes as you want

after_all do |lane|
# This block is called, only if the executed lane was successful

# slack(
#   message: "Successfully deployed new App Update."
# )
end

error do |lane, exception|
# slack(
#   message: exception.message,
#   success: false
# )
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.sharefile.desktop.widget" # The bundle identifier of your app
apple_id "kanth.v.2016@gmail.com" # Your Apple email address

team_id "RM4N8HY7K5"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.5.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| slack-notifier              | 2.3.2        |
| atomos                      | 0.1.2        |
| claide                      | 1.0.2        |
| colored2                    | 3.1.2        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.5.9        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.2.8        |
| addressable                 | 2.5.2        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| public_suffix               | 2.0.5        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| babosa                      | 1.0.2        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| excon                       | 0.62.0       |
| faraday                     | 0.15.2       |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| fastimage                   | 2.1.3        |
| gh_inspector                | 1.1.3        |
| mini_magick                 | 4.5.1        |
| multi_json                  | 1.13.1       |
| multi_xml                   | 0.6.0        |
| rubyzip                     | 1.2.1        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 1.0.0        |
| dotenv                      | 2.5.0        |
| bundler                     | 1.16.3       |
| faraday_middleware          | 0.12.2       |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| mime-types-data             | 3.2016.0521  |
| mime-types                  | 3.1          |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| os                          | 1.0.0        |
| signet                      | 0.8.1        |
| googleauth                  | 0.6.3        |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.23.4       |
| emoji_regex                 | 0.1.1        |
| json                        | 2.1.0        |
| io-console                  | 0.4.5        |
| CFPropertyList              | 3.0.0        |
| libxml-ruby                 | 2.9.0        |
| plist                       | 3.4.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| xctest_list                 | 1.1.3        |
| fastlane-plugin-test_center | 3.5.3        |
</details>

*generated on:* **2018-08-06**
</details>

**Comment by lyndsey-ferguson** [comment]
There is a problem parsing the `xctestrun` file. Would you be willing to list out the directory contents of `../DerivedData/Build/Products/Release/...DesktopUITests-Runner.app` and attach the `xctestrun` file found in the `../DerivedData/Build/Products` directory?

**Comment by homebizjunk** [comment]
Hi ! Thank you for looking into my issue.

The code that I put into Fastfile are as follows:
lane :buildBVT do |options|
    test_run_block = lambda do |testrun_info|
        failed_test_count = testrun_info[:failed].size

        if failed_test_count > 0
            UI.important('The run of tests would finish with failures due to fragile tests here.')

            try_attempt = testrun_info[:try_count]
            if try_attempt < 2
                UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
            end
        end
    end

    result = multi_scan(
        workspace:"../CitrixFiles.xcworkspace",
        scheme: "SFMDriveMapperBVT",
        code_coverage: true,
        derived_data_path: "../DerivedData",
        output_types: "html,junit,json-compilation-database",
        output_directory: "../build/reports/UI_test",
        try_count: 5,
        buildlog_path: "../build/logs/xcodebuild",
        testrun_completed_block: test_run_block
    )
    unless result[:failed_testcount].zero?
        UI.info("There are #{result[:failed_testcount]} legitimate failing tests")
    end
end

Please find attached the structure for the DesktopUITests-Runner.app
![screen shot 2018-08-06 at 2 54 50 pm](https://user-images.githubusercontent.com/42074268/43735574-eff3ba14-9988-11e8-9a91-b0c3a14cc9c5.png)

Please find attached the structure for the xctestrun file
![screen shot 2018-08-06 at 2 55 33 pm](https://user-images.githubusercontent.com/42074268/43735589-fde7750c-9988-11e8-8bef-c0c0d5379f7f.png)

**Comment by homebizjunk** [comment]
The xctestrun file is too large to attached here.

**Comment by lyndsey-ferguson** [comment]
Thanks @homebizjunk, in order to investigate further, I need the file that has the extension `xctestrun`. I'm including an example image and a sample file to help clarify what I am looking for.

<img width="340" alt="screen shot 2018-08-06 at 3 06 25 pm" src="https://user-images.githubusercontent.com/5741516/43736062-6759601c-998a-11e8-91f7-e6c4e6c699d3.png">

[AtomicBoy_iphonesimulator11.1-x86_64.xctestrun.zip](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/2263759/AtomicBoy_iphonesimulator11.1-x86_64.xctestrun.zip)

**Comment by lyndsey-ferguson** [comment]
The `xctestrun` is just a plist file, so I don't imagine it could be too large.

**Comment by homebizjunk** [comment]
Hi lyndsey-ferguson!  Please find the file attached.
[SFMDriveMapperBVT_macosx10.13-x86_64.xctestrun.zip](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/2263915/SFMDriveMapperBVT_macosx10.13-x86_64.xctestrun.zip)

**Comment by homebizjunk** [comment]
Screenshot with the error message![screen shot 2018-08-06 at 4 02 22 pm](https://user-images.githubusercontent.com/42074268/43738336-3fad7866-9992-11e8-9c75-90a383d4ebbc.png)

**Comment by lyndsey-ferguson** [comment]
Thank you, could you also provide the structure of the _parent_ directory for `../DerivedData/Build/Products/Release/...DesktopUITests-Runner.app`?

**Comment by homebizjunk** [comment]
![screen shot 2018-08-06 at 5 08 23 pm](https://user-images.githubusercontent.com/42074268/43741352-105d6ee0-999c-11e8-8899-4de7bdd5cb87.png)

**Comment by homebizjunk** [comment]
Thank you for all your help!

**Comment by lyndsey-ferguson** [comment]
Sorry for being so confusing (I wasn't sure of your directory structure/naming). What about your `DerivedData/Build/Products/Release` directory?

**Comment by homebizjunk** [comment]
![screen shot 2018-08-06 at 6 08 38 pm](https://user-images.githubusercontent.com/42074268/43743432-d33ed208-99a3-11e8-9d47-4ad8b74b56dc.png)

**Comment by lyndsey-ferguson** [comment]
Ok, thank you. I'll be able to investigate this tomorrow morning

**Comment by lyndsey-ferguson** [comment]
I think that the problem is that you are using a relative path for the `:derived_data_path`. Can you update your code to pass in `derived_data_path: File.absolute_path("../DerivedData")` instead of `derived_data_path: "../DerivedData"`?

If you can verify, I can update the plugin code to fix this.

**Comment by homebizjunk** [comment]
Hi @lyndsey-ferguson, I've made code change based on your suggestion and ran it again. I'm still getting the same error.

**Comment by lyndsey-ferguson** [comment]
Okay. Before I start adding logging to the plugin and its action, can you do one more thing?

Change the code in the lane that calls `multi_scan` to be:

```
derived_data_path = File.absolute_path("../DerivedData")
puts "derived_data_path: #{derived_data_path}"
next unless Dir.exist?(derived_data_path)

result = multi_scan(
    workspace:"../CitrixFiles.xcworkspace",
    scheme: "SFMDriveMapperBVT",
    code_coverage: true,
    derived_data_path: derived_data_path,
    output_types: "html,junit,json-compilation-database",
    output_directory: "../build/reports/UI_test",
    try_count: 5,
    buildlog_path: "../build/logs/xcodebuild",
    testrun_completed_block: test_run_block
)
```

If this is not the correct path, fastlane will stop early.

**Comment by homebizjunk** [comment]
@lyndsey-ferguson, I'm still getting the same error after I added the three lines of code as indicated in the screenshot.

![screen shot 2018-08-07 at 12 27 39 pm](https://user-images.githubusercontent.com/42074268/43789191-5a7825a0-9a3d-11e8-96f2-188614a7beb5.png)

**Comment by lyndsey-ferguson** [comment]
And what is the derived data path that is printed to the console?

**Comment by homebizjunk** [comment]
The full path was printed starting from the /Users/........./ShareFileDesktopUITests.xctest/ShareFileDesktopUITests

**Comment by homebizjunk** [comment]
The whole path is as follows: /Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/BuildSystem/DerivedData/Build/Products/Debug/ShareFileDesktopUITests-Runner.app/Contents/PlugIns/ShareFileDesktopUITests.xctest/ShareFileDesktopUITests

**Comment by homebizjunk** [comment]
Yes, it is.  "sfdesktop" is the project name in Jenkins.

**Comment by lyndsey-ferguson** [comment]
I have added logging to the tool in the branch `issue-63-cant-find-xctest-binary`. Can you modify your `Pluginfile` from:

```ruby
gem 'fastlane-plugin-test_center'
```
to:

```ruby
gem 'fastlane-plugin-test_center', :git => "git://github.com/lyndsey-ferguson/fastlane-plugin-test_center.git", :branch => "issue-63-cant-find-xctest-binary"
```

Then run your `:buildBVT` lane again. When it fails, please attach the `issue_63_log.txt` file (in your `:output_directory`) to this Issue.

Thanks!

**Comment by homebizjunk** [comment]
@lyndsey-ferguson  I replaced the line as you instructed and ran the :buildBVT lane. I don't see the issue_63_log.txt file got generated where the output_directory is located.  ![screen shot 2018-08-08 at 11 52 40 pm](https://user-images.githubusercontent.com/42074268/43877286-f6c68f58-9b66-11e8-892e-ed7bcc451ef4.png)

**Comment by homebizjunk** [comment]
Hi @lyndsey-ferguson, Is there something else missing for not getting the log file generated then?

**Comment by lyndsey-ferguson** [comment]
Nope, you just need to `bundle install` then run the `:buildBVT` lane again.

**Comment by homebizjunk** [comment]
I ran "bundle install" already last night before I ran fastlane. That's why I attached the screenshot to show that I ran the "bundle install".  It didn't generate the log file.

**Comment by lyndsey-ferguson** [comment]
I added a log statement as soon as `:multi_scan` starts to print out the log file location.

**Comment by lyndsey-ferguson** [comment]
you may need to remove the `fastlane-plugin-test_center` entries from the `Gemfile.lock` for the updated version to take.

**Comment by lyndsey-ferguson** [comment]
https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/issue-63-cant-find-xctest-binary/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L14

**Comment by homebizjunk** [comment]
There are two entries for fastlane-plugin-test_center in the Gemfile.lock file. Which one should I be removing? There is one entry under GIT, the other entry is under Dependencies.
![screen shot 2018-08-09 at 1 42 29 pm](https://user-images.githubusercontent.com/42074268/43916025-70174942-9bda-11e8-8237-02e81aa63de8.png)
![screen shot 2018-08-09 at 1 43 10 pm](https://user-images.githubusercontent.com/42074268/43916033-75f035c2-9bda-11e8-8b69-7a74da6e0ebd.png)

**Comment by lyndsey-ferguson** [comment]
First, remove the entire GIT entry. Then, in dependencies, remove that one too.

OR, can you remove the Gemfile.lock file for now?

**Comment by lyndsey-ferguson** [comment]
@homebizjunk would you be able to remove the `Gemfile.lock` file for testing this? That would be the easiest and most reliable step.

**Comment by homebizjunk** [comment]
Sorry, I've been tied up with other more urgent work.  I'm trying it now.

**Comment by homebizjunk** [comment]
I removed the Gemfile.lock file and ran "bundle install" and then ran "fastlane buildBVT". For some reason, I'm still unable to generate the log file that you mentioned above.
Looks like it is fetching the test_center from the right branch
![screen shot 2018-08-10 at 12 11 04 pm](https://user-images.githubusercontent.com/42074268/43969024-d60596e8-9c96-11e8-9e5d-c0a9fc6811c5.png)
![screen shot 2018-08-10 at 12 13 09 pm](https://user-images.githubusercontent.com/42074268/43969026-da559fc2-9c96-11e8-926e-d50b263f1595.png)

**Comment by homebizjunk** [comment]
This is what is printed on the console. 
![screen shot 2018-08-10 at 4 27 09 pm](https://user-images.githubusercontent.com/42074268/43979915-483415e6-9cba-11e8-816e-6abdc475a3b2.png)

**Comment by lyndsey-ferguson** [comment]
Does the file end up being put in `../build/reports/UI_test`? **OR** do you see an **extra** `build` directory up one level from where you are expecting your results?

**Comment by lyndsey-ferguson** [comment]
I've updated the code to output the absolute path. Now that we know that the log file is being created, you can remove the `byebug` command and let it run as normal.

**Comment by lyndsey-ferguson** [comment]
I will try resetting the specific simulator via:
```
FastlaneCore::Simulator.reset(udid:'67C5D0A4-A1A8-4407-8152-EEB28BE02C27')
```
where id comes from:
```
config[:destination] # ["platform=iOS Simulator", "id=67C5D0A4-A1A8-4407-8152-EEB28BE02C27"]
```

**Comment by lyndsey-ferguson** [comment]
Resetting seems to work

**Comment by lyndsey-ferguson** [comment]
Next, pull out the code so that `fork`ing happens programmatically. Then, we have to create duplicate the chosen simulator and delete them when done.

**Comment by homebizjunk** [comment]
Hi @lyndsey-ferguson! Please find the issue_63 log file attached. [issue_63_log.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/2283577/issue_63_log.txt)

**Comment by lyndsey-ferguson** [comment]
Does it still fail? The log indicates that it found the `xctest` bundle:
```
path: /Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/BuildSystem/DerivedData/Build/Products/Debug/ShareFileDesktopUITests-Runner.app/Contents/PlugIns/ShareFileDesktopUITests.xctest
path exist? true
```

**Comment by homebizjunk** [comment]
I don't know if it is important.  I found the issue_63_log.txt file in 
/Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/build/reports/UI_test not in the folder that I expected 
/Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/BuildSystem/build/reports/UI_test

**Comment by homebizjunk** [comment]
@lyndsey-ferguson , Yes, it is still failing.  
(byebug) n
[11:18:41]: Missing xctest binary: '/Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/BuildSystem/DerivedData/Build/Products/Debug/ShareFileDesktopUITests-Runner.app/Contents/PlugIns/ShareFileDesktopUITests.xctest/ShareFileDesktopUITests'

**Comment by lyndsey-ferguson** [comment]
Yes, the log file not being placed into the expected directory is an issue. It is not *the* issue though.

What is inside the bundle at `'/Users/calvinchang/Documents/LatestCFMacGA/sfdesktop/BuildSystem/DerivedData/Build/Products/Debug/ShareFileDesktopUITests-Runner.app/Contents/PlugIns/ShareFileDesktopUITests.xctest`? 

_You can right click the `xctest` file and select "Show Package Contents"_

**Comment by homebizjunk** [comment]
![](https://user-images.githubusercontent.com/42074268/43735589-fde7750c-9988-11e8-8bef-c0c0d5379f7f.png)

**Comment by lyndsey-ferguson** [comment]
Ah, how odd. It makes sense that the actual binary is in a `Contents/MacOS` directory. That makes sense too. Which version of Xcode are using?

**Comment by homebizjunk** [comment]
Xcode 9.4.1
Build version 9F2000

**Comment by lyndsey-ferguson** [comment]
I created [this Issue](https://github.com/lyndsey-ferguson/xctest_list/issues/2). Tomorrow I'll make a test build for us.

**Comment by homebizjunk** [comment]
Thank you, @lyndsey-ferguson!

**Comment by lyndsey-ferguson** [comment]
@homebizjunk okay, here are the steps to get the dev plugins and gems into your project.

1. Remove your `Gemfile.lock` file again.
2. Keep your `Pluginfile` so that it still refers to the `fastlane-plugin-test_center` plugin that we're using for debugging:
  ```
  gem 'fastlane-plugin-test_center', :git => 'https://github.com/lyndsey-ferguson/fastlane-plugin-test_center', :branch => 'issue-63-cant-find-xctest-binary'
  ```
3. Update your `Gemfile` to include:
  ```
  gem 'xctest_list', :git => 'https://github.com/lyndsey-ferguson/xctest_list', :branch => 'issue-2-unable-to-find-binary'
  ```
4. Run `bundle install`
5. Run `bundle exec fastlane buildBVT`
6. Observe. Does it complete? 🤞

**Comment by homebizjunk** [comment]
@lyndsey-ferguson, I'm sorry! I've been busy with other urgent work.  I should be able to get to try it soon. I'll keep you posted. Thank you!

**Comment by lyndsey-ferguson** [comment]
We are almost there, I'm sure this will fix it, but want your 👍

**Comment by homebizjunk** [comment]
@lyndsey-ferguson I'm sorry to inform you that I'm seeing the same result. 
![screen shot 2018-08-14 at 4 13 58 pm](https://user-images.githubusercontent.com/42074268/44115928-1eef0274-9fdd-11e8-85d5-adc538193717.png)

![screen shot 2018-08-14 at 4 14 42 pm](https://user-images.githubusercontent.com/42074268/44115965-36430a1a-9fdd-11e8-81ca-49ec45ac5324.png)


![screen shot 2018-08-14 at 4 09 41 pm](https://user-images.githubusercontent.com/42074268/44115835-e0bf4fae-9fdc-11e8-8936-c1ece74817e1.png)

**Comment by lyndsey-ferguson** [comment]
Yeah, that's because it is using the last released `xctest_list`. The branch that I tried to get setup for your build doesn't have that [code at line 27](https://github.com/lyndsey-ferguson/xctest_list/blob/issue-2-unable-to-find-binary/lib/xctest_list.rb#L27).

**Comment by lyndsey-ferguson** [comment]
Oh, could you include this step (selecting `All versions`):
```
gem uninstall xctest_list
```
And then run the [above steps](
https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/63#issuecomment-412871932)
```

**Comment by homebizjunk** [comment]
The fix works.  The process went past the point where it was failing. I've got some other error to look into. Thank you soooooooooo much for your time and effort to help!  I really appreciate that.
![screen shot 2018-08-14 at 6 05 49 pm](https://user-images.githubusercontent.com/42074268/44121179-059600ec-9fed-11e8-9d01-3c800fa3d507.png)

**Comment by lyndsey-ferguson** [comment]
@homebizjunk thank you for your help in debugging this. I have [released a new version of this plugin](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.5.4) that uses the fixed `xctest_list` gem.
