### ISSUE TITLE
Re-running scan on only failed tests is failing because tests_from_junit does not declare it works with Mac

### ISSUE THREAD

**Issue by homebizjunk** [lyndsey-ferguson/fastlane-plugin-test_center#64]
@lyndsey-ferguson The multi_scan seems to be failing as soon as it starts to re-run of the failed test case.

The is what I have in the Fastfile:
```ruby
lane :buildBVT do |options|
    clean_uiautomationtest
    test_run_block = lambda do |testrun_info|
    failed_test_count = testrun_info[:failed].size

    if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')

        try_attempt = testrun_info[:try_count]
            if try_attempt < 2
                UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
            end
        end
    end

    result = multi_scan(
        workspace:"../CitrixFiles.xcworkspace",
        scheme: "SFMDriveMapperBVT",
        code_coverage: true,
        derived_data_path: "./DerivedData",
        output_types: "html,junit,json-compilation-database",
        output_directory: "./build/reports/UI_test",
        try_count: 5,
        buildlog_path: "./build/logs/xcodebuild",
        testrun_completed_block: test_run_block
    )
    unless result[:failed_testcount].zero?
        UI.info("There are #{result[:failed_testcount]} legitimate failing tests")
    end
end
```

===========================================================
The result of the "bundle exec fastlane buildBVT"  is as follows:

Selected tests
Test Suite ShareFileDesktopUITests.xctest started
SFMBVTTest
✓ test_bvt (0.417 seconds)
BVTTestcase
✗ test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
✗ test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
✗ test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
✓ test_NoFolderPermissionOptionForNonAdminUser_TC_2441 (50.349 seconds)
✓ test_ViewOnlyPermissionIsChecked_TC_2405 (55.321 seconds)
✓ test_ModifyUserPermission_TC_2425 (44.712 seconds)
✓ test_ModifySingleUserFolderPermission_TC_2431 (43.279 seconds)
✓ test_ManageFolderPermissionInContextMenuFavoriteFolder_TC_2406 (12.291 seconds)
✓ test_ManageFolderPermissionInContextMenuPersonalFolder_TC_2407 (11.804 seconds)
✓ test_ManageFolderPermissionInContextMenuShareFolder_TC_2408 (14.331 seconds)
✓ test_Preview_Option_Not_Exist_For_Network_Shares_Connector_TC_2390 (38.177 seconds)

ShareFileDesktopUITests.FolderPermissionTests
test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
FolderPermissionTests.swift:300

test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
FolderPermissionTests.swift:300

test_RemoveSelectedMultipleUsers_TC_2413, XCTAssertTrue failed - Fail to remove users
FolderPermissionTests.swift:300

	 Executed 1 test, with 0 failures (0 unexpected) in 0.417 (324.126) seconds

Failing tests:
BVTTestcase.test_RemoveSelectedMultipleUsers_TC_2413()
** TEST EXECUTE FAILED **
[13:01:25]: Exit status: 65
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 12 |
| Number of failures | 3  |
+--------------------+----+

[13:01:25]: The run of tests would finish with failures due to fragile tests here.
[13:01:25]: -------------------------------------------------------------------------------
[13:01:25]: --- Since we are using :multi_scan, we can re-run just those failing tests! ---
[13:01:25]: -------------------------------------------------------------------------------
[13:01:25]: Re-running scan on only failed tests
[13:01:26]: $ xcodebuild -showBuildSettings -workspace ../CitrixFiles.xcworkspace -scheme SFMDriveMapperBVT
[13:01:29]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[13:01:32]: $ xcodebuild -showBuildSettings -workspace ../CitrixFiles.xcworkspace -scheme SFMDriveMapperBVT
[13:01:35]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

+----------------------------+------------------------------------------------------------+
|                                Summary for scan 2.101.1                                 |
+----------------------------+------------------------------------------------------------+
| workspace                  | ../CitrixFiles.xcworkspace                                 |
| scheme                     | SFMDriveMapperBVT                                          |
| derived_data_path          | ./DerivedData                                              |
| buildlog_path              | ./build/logs/xcodebuild                                    |
| test_without_building      | true                                                       |
| skip_build                 | false                                                      |
| include_simulator_logs     | false                                                      |
| disable_concurrent_testing | false                                                      |
| should_zip_build_products  | false                                                      |
| result_bundle              | false                                                      |
| open_report                | false                                                      |
| skip_slack                 | false                                                      |
| slack_only_on_failure      | false                                                      |
| use_clang_report_name      | false                                                      |
| clean                      | false                                                      |
| output_directory           | ./build/reports/UI_test                                    |
| only_testing               | ["ShareFileDesktopUITests/FolderPermissionTests/test_Remo  |
|                            | veSelectedMultipleUsers_TC_2413",                          |
|                            | "ShareFileDesktopUITests/FolderPermissionTests/test_Remov  |
|                            | eSelectedMultipleUsers_TC_2413",                           |
|                            | "ShareFileDesktopUITests/FolderPermissionTests/test_Remov  |
|                            | eSelectedMultipleUsers_TC_2413"]                           |
| output_types               | html,junit,json-compilation-database                       |
| output_files               | report-2.html,report-2.junit,report-2.json-compilation-da  |
|                            | tabase                                                     |
| fail_build                 | true                                                       |
| xcode_path                 | /Applications/Xcode.app                                    |
+----------------------------+------------------------------------------------------------+

...

[13:01:38]: ▸ Loading...
[13:01:40]: ▸ 2018-08-15 13:01:40.227 xcodebuild[13350:254387]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[13:01:40]: ▸ /var/folders/ly/wy73cfcd741b95x0_nn4c2pw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-622A2E3E-C286-4785-8E7C-61FEA80CC16F/ShareFileDesktopUITests-5250E757-45F0-4957-AD71-3DBD698DBCB8/Session-ShareFileDesktopUITests-2018-08-15_130140-aCNAAt.log
[13:01:40]: ▸ 2018-08-15 13:01:40.228 xcodebuild[13350:254375] [MT] IDETestOperationsObserverDebug: (974C5E54-AEF7-40FC-AFC7-0555C3F3833E) Beginning test session ShareFileDesktopUITests-974C5E54-AEF7-40FC-AFC7-0555C3F3833E at 2018-08-15 13:01:40.228 with Xcode 9F2000 on target <DVTLocalComputer: 0x7fa0f2d77400 (My Mac | x86_64h)> (10.13.6 (17G65))
[13:01:40]: ▸ Selected tests
[13:01:40]: ▸ Test Suite ShareFileDesktopUITests.xctest started
[13:01:40]: ▸ 	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds
[13:01:40]: ▸ 
[13:01:41]: ▸ Test execute Succeeded
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+

[13:01:41]: Action 'tests_from_junit' isn't known to support operating system 'mac'.

+------------------------------------------------------------+------------------------------------------------------------+
|                                                   multi_scan results                                                    |
+------------------------------------------------------------+------------------------------------------------------------+
| result                                                     | true                                                       |
| total_tests                                                | 12                                                         |
| passing_testcount                                          | 9                                                          |
| failed_testcount                                           | 3                                                          |
| failed_tests                                               | ["ShareFileDesktopUITests/FolderPermissionTests/test_Remo  |
|                                                            | veSelectedMultipleUsers_TC_2413",                          |
|                                                            | "ShareFileDesktopUITests/FolderPermissionTests/test_Remov  |
|                                                            | eSelectedMultipleUsers_TC_2413",                           |
|                                                            | "ShareFileDesktopUITests/FolderPermissionTests/test_Remov  |
|                                                            | eSelectedMultipleUsers_TC_2413"]                           |
| failure_details.ShareFileDesktopUITests/FolderPermissionT  | XCTAssertTrue failed - Fail to remove users                |
| ests/test_RemoveSelectedMultipleUsers_TC_2413.message      |                                                            |
| failure_details.ShareFileDesktopUITests/FolderPermissionT  |          FolderPermissionTests.swift:300                   |
| ests/test_RemoveSelectedMultipleUsers_TC_2413.location     |                                                            |
| total_retry_count                                          | 1                                                          |
| report_files                                               | ["/Users/calvinchang/Documents/CFMac4_2/sfdesktop/BuildSy  |
|                                                            | stem/build/reports/UI_test/report.junit",                  |
|                                                            | "/Users/calvinchang/Documents/CFMac4_2/sfdesktop/BuildSys  |
|                                                            | tem/build/reports/UI_test/report.html"]                    |
+------------------------------------------------------------+------------------------------------------------------------+

+------------------------------+------------------------------------------------------------+
|                                       Lane Context                                        |
+------------------------------+------------------------------------------------------------+
| DEFAULT_PLATFORM             | mac                                                        |
| PLATFORM_NAME                | mac                                                        |
| LANE_NAME                    | mac buildBVT                                               |
| XCODEBUILD_DERIVED_DATA_PATH |                                                            |
| SCAN_DERIVED_DATA_PATH       | ./DerivedData                                              |
| SCAN_GENERATED_PLIST_FILES   | ["./DerivedData/Logs/Test/E333FF50-26FE-466F-B707-C35117C  |
|                              | 4B000_TestSummaries.plist"]                                |
| SCAN_GENERATED_PLIST_FILE    | ./DerivedData/Logs/Test/E333FF50-26FE-466F-B707-C35117C4B  |
|                              | 000_TestSummaries.plist                                    |
+------------------------------+------------------------------------------------------------+
[13:01:41]: Unknown method 'info', supported [:select, :message, :verbose, :error, :input, :password, :header, :command, :success, :confirm, :important, :user_error!, :command_output, :deprecated, :content_error, :interactive?, :crash!, :not_implemented, :shell_error!, :build_failure!, :test_failure!, :abort_with_message!]

+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | opt_out_usage                         | 0           |
| 2    | default_platform                      | 0           |
| 3    | Switch to mac clean_uiautomationtest  | 0           |
|      | lane                                  |             |
| 4    | cd .. && rm -rf build/DerivedData/    | 0           |
| 5    | killall 'iOS Simulator' 'iPhone       | 0           |
|      | Simulator' 'Simulator' || tru         |             |
| 6    | xcclean                               | 4           |
| 7    | multi_scan                            | 393         |
+------+---------------------------------------+-------------+

**Comment by lyndsey-ferguson** [comment]
```
[13:01:41]: Action 'tests_from_junit' isn't known to support operating system 'mac'.
```
😱 
So, it is failing to get the failing tests, and it freaks out. That explains the format of your `xctest` bundle, you're testing a Mac target!

**Comment by lyndsey-ferguson** [comment]
Congrats @homebizjunk, you are my first known Mac developer! The others have been iOS devs.

**Comment by homebizjunk** [comment]
@lyndsey-ferguson How lucky I am!

**Comment by lyndsey-ferguson** [comment]
Can you modify your `Pluginfile` again and re-run `bundle install`?

Pluginfile:
```
gem 'fastlane-plugin-test_center', :git => "git://github.com/lyndsey-ferguson/fastlane-plugin-test_center.git", :branch => "issue-64-mac-support"
```

**Comment by homebizjunk** [comment]
@lyndsey-ferguson  should I keep the change in the Gemfile?

gem 'xctest_list', :git => 'https://github.com/lyndsey-ferguson/xctest_list', :branch => 'issue-2-unable-to-find-binary'

**Comment by lyndsey-ferguson** [comment]
You can remove the `xctest_list` item from your `Gemfile`

**Comment by homebizjunk** [comment]
@lyndsey-ferguson , No longer seeing the error "Action" message. But it is not re-running the failed test case.
![screen shot 2018-08-15 at 5 56 11 pm](https://user-images.githubusercontent.com/42074268/44175640-d56c4480-a0b4-11e8-9cc9-8b484cdf69fd.png)

**Comment by lyndsey-ferguson** [comment]
Ug, my example has to be fixed, change your lane from:
```
unless result[:failed_testcount].zero?
    UI.info("There are #{result[:failed_testcount]} legitimate failing tests")
end
```
to:
```
unless result[:failed_testcount].zero?
    UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
end
```

**Comment by lyndsey-ferguson** [comment]
Basically, everything worked and it was about to declare that there were test failures

**Comment by lyndsey-ferguson** [comment]
Ah, it could be that you have more than 1 test target and the first test target had failures, and the second one did not?

**Comment by lyndsey-ferguson** [comment]
@homebizjunk I believe that I fixed the issue that you reported and then we found with the README example that you used, so I am closing this Issue. If we find that the tests are not retrying, can you open a new Issue and include the entire log in text format?
