### ISSUE TITLE
Feature Request: multi_scan to generate a single report for projects with multiple test targets

### ISSUE THREAD

**Issue by littlebobert** [lyndsey-ferguson/fastlane-plugin-test_center#69]
### Feature Request
It would be cool if multi_scan could generate a single report for projects with multiple test targets.

#### Motivation Behind Feature

The built-in `scan` lane can generate a single report for multiple test targets, and it’s nice to be able to see that when its finished running the tests.

#### Feature Description

In https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/41 you mention that the reports can’t be merged because of the format they use. Maybe this feature request should live in its own plugin?

#### Alternatives or Workarounds

I’m not sure if there is a workaround.

**Comment by lyndsey-ferguson** [comment]
Do you have an idea of how this would work? Are you specifically asking for 'JUnit' style reports to be consolidated for the test target results? From what I understand of the format, each report has one "root" node. That root node in the way that `xcpretty` formats it is the test target itself.

I suppose that one could create a node at a "higher" level and the direct children would be the test targets.

**Comment by lyndsey-ferguson** [comment]
Started [project](https://github.com/fastlane-plugin-test-center/fastlane-plugin-test_center/projects/2)

**Comment by lyndsey-ferguson** [comment]
[v3.14.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/docs/feature_details/multi_scan.md#better-results-reporting) now supports the collation of junit reports generated for different test targets.

**Comment by lyndsey-ferguson** [comment]
Released to the public in [v3.14.3](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.14.3)
