### ISSUE TITLE
[Multi-scan]Failing tests aren't being re-run and the tests are subsequently being marked as passed

### ISSUE THREAD

**Issue by zacoid55** [lyndsey-ferguson/fastlane-plugin-test_center#7]
Running multiscan on a broken test will successfully report the test as broken the once but when it tries to re-run the broken test it won't restart the broken tests and will just repeat the same error text as before i.e.:

```
[16:37:45]: ▸ JourneyFeature
[16:37:56]: ▸ ✗ test_loginTypes, XCTAssertTrue failed -
[16:37:56]: ▸ UITests.JourneyFeature
[16:37:56]: ▸ test_loginTypes, XCTAssertTrue failed - 
[16:37:56]: ▸ LoginTypesSteps.swift:31
[16:37:56]: ▸ 	 Executed 1 test, with 1 failure (0 unexpected) in 11.288 (11.290) seconds
```

Followed by:

```
JourneyFeature
✗ test_loginTypes, XCTAssertTrue failed -


TescoTitanUITests.JourneyFeature
test_loginTypes, XCTAssertTrue failed - 
LoginTypesSteps.swift:31


	 Executed 1 test, with 1 failure (0 unexpected) in 11.288 (11.290) seconds
```
And then after this failure, the test will still be picked up as successful even with this report underneath: 
```
** TEST EXECUTE FAILED **
[16:38:02]: Exit status: 65
[16:38:03]: Successfully sent Slack notification
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 1 |
| Number of failures | 1 |
```

**Comment by zacoid55** [comment]
I can only think it can't do this because it's running from a workspace instead of a proj?

**Comment by lyndsey-ferguson** [comment]
I've reproduced the error.

**Comment by lyndsey-ferguson** [comment]
@zacoid55 what did you set your `:try_count` to? It works fine for me. Can you post how you are calling `multi_scan`?

**Comment by zacoid55** [comment]
@lyndsey-ferguson I didn't know there was a `:try_count` option :O - I will try that now

**Comment by zacoid55** [comment]
@lyndsey-ferguson yeah that worked, mate - thank you. I just had to put a `try_count` > 1 and it kicked into gear - thank you!

**Comment by lyndsey-ferguson** [comment]
One benefit is that I updated the action to print out the summary and improved the examples to show `:try_count` with the project and workspace options.

**Comment by zacoid55** [comment]
Just saw that, really handy man. Thank you so much
