### ISSUE TITLE
multi_scan produces lots of extraneous dashes and spaces in console output when running on circle

### ISSUE THREAD

**Issue by littlebobert** [lyndsey-ferguson/fastlane-plugin-test_center#71]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

##### Complete output when running fastlane, including the stack trace and command used

This is the console output for just a single test target, called CoreTests. GitHub is eating some of the spaces when I paste them into the issue template, so I’m including a text file of the output in my comment below.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.13.3                                         |
| Ruby                        | 2.4.4                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.17.1                              |
| Installation Source         | ~/project/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.13.3 (17D102)                       |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.4/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.4.app/Contents/Developer/ |
| Xcode Version               | 9.4                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import 'GeneralFastFile'

default_platform :ios

platform :ios do
  lane :circleci do |options|
    cocoapods
    circleci_build(clean: true)
    circleci_test(open_report: true)
  end

  lane :circleci_build do |options|
    scan_lane(
      'Build',
      build_for_testing: true,
      xcargs:            'CODE_SIGNING_REQUIRED=NO -quiet',
      clean:             options.fetch(:clean, false)
    )
  end

  lane :circleci_test do |options|
    begin
      result = multi_scan(
        workspace: File.absolute_path('../Procore.xcworkspace'),
        try_count: 3,
        test_without_building: true,
        scheme: scan_defaults.fetch(:scheme),
        devices: scan_defaults.fetch(:devices),
        output_types: 'html,junit'
      )
      unless result[:failed_testcount].zero?
        raise "There were #{result[:failed_testcount]} failing test(s)."
      end
    rescue => exception
      on_error('Test', exception)
      raise exception
    end
  end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.5.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.1.0        |
| bundler                     | 1.16.2       |
| io-console                  | 0.4.6        |
| CFPropertyList              | 3.0.0        |
| concurrent-ruby             | 1.0.5        |
| i18n                        | 0.9.5        |
| minitest                    | 5.11.3       |
| thread_safe                 | 0.3.6        |
| tzinfo                      | 1.2.5        |
| activesupport               | 4.2.10       |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| atomos                      | 0.1.3        |
| babosa                      | 1.0.2        |
| claide                      | 1.0.2        |
| fuzzy_match                 | 2.0.4        |
| nap                         | 1.1.0        |
| cocoapods-core              | 1.4.0        |
| cocoapods-deintegrate       | 1.0.2        |
| cocoapods-downloader        | 1.1.3        |
| cocoapods-plugins           | 1.0.0        |
| cocoapods-search            | 1.0.0        |
| cocoapods-stats             | 1.0.0        |
| netrc                       | 0.11.0       |
| cocoapods-trunk             | 1.3.0        |
| cocoapods-try               | 1.1.0        |
| colored2                    | 3.1.2        |
| escape                      | 0.0.4        |
| fourflusher                 | 2.0.1        |
| gh_inspector                | 1.1.3        |
| molinillo                   | 0.6.5        |
| ruby-macho                  | 1.1.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.6.0        |
| cocoapods                   | 1.4.0        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| dotenv                      | 2.5.0        |
| emoji_regex                 | 0.1.1        |
| excon                       | 0.62.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.2       |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.4        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| multi_json                  | 1.13.1       |
| os                          | 1.0.0        |
| signet                      | 0.9.1        |
| googleauth                  | 0.6.6        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2018.0812  |
| mime-types                  | 3.2.2        |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| json                        | 2.1.0        |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.4.0        |
| rubyzip                     | 1.2.2        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 1.8.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| word_wrap                   | 1.0.0        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| xctest_list                 | 1.1.4        |
| fastlane-plugin-test_center | 3.5.7        |
</details>

*generated on:* **2018-09-14**
</details>

**Comment by littlebobert** [comment]
[CoreTests-output.txt](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/2384021/CoreTests-output.txt)

**Comment by lyndsey-ferguson** [comment]
Ug, that's because the tests wrap around and make the header crazy.

**Comment by lyndsey-ferguson** [comment]
I think that there may be a possibility of tweaking what the print table code _thinks_ is the width that it can print to. I've seen newer versions of scan printing nice tables.

**Comment by lyndsey-ferguson** [comment]
@littlebobert is this still happening? I want to know before I start looking into fixing this.

**Comment by lyndsey-ferguson** [comment]
This is no longer happening! 🎉
