### ISSUE TITLE
Support for Xcode 10 Parallel Testing Feature

### ISSUE THREAD

**Issue by cisum-la** [lyndsey-ferguson/fastlane-plugin-test_center#72]
#### Motivation Behind Feature
Xcode 10 provides parallel testing feature,  https://www.zachsim.one/blog/2018/6/15/parallel-testing-in-xcode-10 whereby testsuites of xctest and xcuitests are split for running into multiple simulator clones. This significantly reduces total test time by around half or even more. However, this feature leads to a bit more test flakiness in my experience. It would be great to be able to re-run these tests using fastlane-plugin-test_center.
Not sure if someone has already entered this request - if so then please feel free to mark it duplicate.

**Comment by lyndsey-ferguson** [comment]
Hi @cisum-la, thans for the suggestion and welcome to the repo! Yes, someone has already [submitted this issue](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/10) and it is in progress. It is functional, but messy and I am cleaning it up before releasing it.

I'll close this as it is a duplicate.
