### ISSUE TITLE
Separate reports for each run

### ISSUE THREAD

**Issue by zacoid55** [lyndsey-ferguson/fastlane-plugin-test_center#8]
Interesting feature request for you, @lyndsey-ferguson... When running X runs on the tests, would there be anyway to append something like (1), (2), (3) etc to the end of the name of the output files?

Right now if your try_count is 3 - and all 3 retest runs are carried out, you'll end up with a report.html with only the retried tests.

**Comment by lyndsey-ferguson** [comment]
Good idea, I do have that for the xml files (I believe) but there is a problem with it that I am looking into.

Thanks for the idea!

**Comment by zacoid55** [comment]
Yeah the xml files do something like that - though it starts with a .junit and the duplicates are .xmls.

Nps

**Comment by lyndsey-ferguson** [comment]
Fixed with [v2.2.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v2.2.0)
