### ISSUE TITLE
Is there a way to pin the plugin version? If yes, how?

### ISSUE THREAD

**Issue by jineshqa** [lyndsey-ferguson/fastlane-plugin-test_center#82]
### Question Checklist

- [X] Updated `fastlane-plugin-test_center` to the latest version
- [X] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [X] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [X] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

### Question Subject
What tool/action do you have a question about?  --> test_center plugin
Is this a question about documentation?  --> No
Is this a question about a fastlane? (If so, please go to the fastlane repository first)  --> No

#### Question Description
Is there a way to pin the plugin version? If yes, how? I am currently on 3.6.9 and it's working great for me. I was wondering if I can pin this version for my project to avoid any break due to newer versions.

**Comment by lyndsey-ferguson** [comment]
You should have a Gemfile.lock file. If you keep the version of 3.6.9, it should effectively pin it. Let me know if this helps.

**Comment by jineshqa** [comment]
Should I update it as below?
`DEPENDENCIES
  fastlane
  fastlane-plugin-test_center (~> 3.6.9)`

**Comment by lyndsey-ferguson** [comment]
That looks right

**Comment by lyndsey-ferguson** [comment]
@jineshqa please let me know if this information resolves your question. I will close this Issue in a few days if yes, or if I don't hear back from you in a few days.

**Comment by jineshqa** [comment]
I am closing the issue, will reopen if this does not work. Thank you for prompt response.
