### ISSUE TITLE
multi_scan option to not kill simulators before test

### ISSUE THREAD

**Issue by amelendezSGY** [lyndsey-ferguson/fastlane-plugin-test_center#88]
#### Motivation Behind Feature
I have a small handful of UI tests that either MUST run, OR run more stably, in a non-headless context. Being able to configure whether multi_scan makes the internal call to "quit_simulators" would be very helpful to me,

#### Feature Description
The multi_scan action could expose a new boolean configuration parameter like "kill_sims". Based on its value, the "correcting_scan" function in "CorrectingScanHelper" would optionally call "quit_simulators". For example:
```ruby
  result = multi_scan(
    project: MY_XCODE_PROJECT_FILEPATH,
    try_count: 3,
    fail_build: false,
    scheme: 'NonHeadlessTests',
    testrun_completed_block: test_run_block,
    kill_sims: false
  )
```
The default value for the "kill_sims" parameter could be "true" to maintain existing functionality.

#### Alternatives or Workarounds
My current alternative is to have a customized lane for the tests that I know can't run headlessly. This lane has custom steps to ensure that the simulator application is open on the host machine and simply calls "scan". This does not allow me to get the benefits afforded by test_center :(

**Comment by lyndsey-ferguson** [comment]
You can get around this by overriding the method that does this.

Add this code:
```ruby

module TestCenter
  module Helper
    class CorrectingScanHelper
      def quit_simulators
        puts 'not quitting simulators`
      end
    end
  end
end
```

**OR**

You could create a PR to add this functionality. I would welcome the help.

**Comment by amelendezSGY** [comment]
Thanks for the reply and your suggestion. I'll take a thwack at it and submit a PR. What are your thoughts about the setting instead indicating whether or not to run the tests headlessly? The default could be to run them headlessly (as is the current default behavior, thanks to the quit_simulators call). But if the user opts to not run them headlessly, a utility function would run to ensure the simulator application is launched prior to kicking off the test. I've currently got something like that in my fastfile that looks similar to this:
```ruby
def launchSimulator()
    sh "open #{ENV['DEVELOPER_DIR']}/Applications/Simulator.app"
end
```

**Comment by lyndsey-ferguson** [comment]
Unless I misunderstand the suggestion, `scan`, upon which `multi_scan` is based, already offers the ability to pre-open the simulator via the `ENV` key `'FASTLANE_EXPLICIT_OPEN_SIMULATOR'`. For more info, see the [code](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/runner.rb#L160).

Would that address your suggestion?

**Comment by lyndsey-ferguson** [comment]
Addressed in [v3.6.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.6.0)

**Comment by amelendezSGY** [comment]
Thank you! Looking forward to taking it for a test drive!

**Comment by lyndsey-ferguson** [comment]
@amelendezSGY thank you for sponsoring me as a fan! 🎉
