### ISSUE TITLE
Status of tests comes out as Warning status when running from Jenkins

### ISSUE THREAD

**Issue by zacoid55** [lyndsey-ferguson/fastlane-plugin-test_center#9]
I'm using multi_scan within our Jenkins box now but I'm seeing the status of the builds come out as Yellow or "Warning" when the tests all succeed but they succeed after a couple of runs. E.g. 4 tests pass, 1 test fails on the first run and then the 1 test passes on the next run.

This results in a warning status to the jenkins build

**Comment by lyndsey-ferguson** [comment]
Fixed in [v2.2.1](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v2.2.1).
