### ISSUE TITLE
multi_scan's collated test_result bundle does not include passed test cases

### ISSUE THREAD

**Issue by SathyaNarayanCodeX** [lyndsey-ferguson/fastlane-plugin-test_center#94]
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

### Description

The final collated test_result bundle does _not_ include passed cases.

**Comment by lyndsey-ferguson** [comment]
`multi_scan` does not support `xchtml`. Please create a [feature request](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/new?template=FEATURE_REQUEST.md) and fill in the form.

**Comment by SathyaNarayanCodeX** [comment]
I was able to create a **xchtml report** for all my runs.

**Comment by SathyaNarayanCodeX** [comment]
Attaching logs where you could see the report being created.

`✔] 🚀 
+-----------------------------+---------+---------------------------------------------+
|                                    Used plugins                                     |
+-----------------------------+---------+---------------------------------------------+
| Plugin                      | Version | Action                                      |
+-----------------------------+---------+---------------------------------------------+
| fastlane-plugin-test_center | 3.6.2   | suppressed_tests suppress_tests             |
|                             |         | suppress_tests_from_junit                   |
|                             |         | tests_from_xctestrun                        |
|                             |         | collate_test_result_bundles                 |
|                             |         | tests_from_junit multi_scan                 |
|                             |         | collate_html_reports collate_junit_reports  |
|                             |         | collate_json_reports                        |
+-----------------------------+---------+---------------------------------------------+

[18:42:49]: ----------------------------------------
[18:42:49]: --- Step: Verifying fastlane version ---
[18:42:49]: ----------------------------------------
[18:42:49]: Your fastlane version 2.115.0 matches the minimum requirement of 2.57.1  ✅
[18:42:49]: ------------------------------
[18:42:49]: --- Step: default_platform ---
[18:42:49]: ------------------------------
[18:42:50]: Driving the lane 'ios run_ui_tests' 🚀
[18:42:50]: ------------------------
[18:42:50]: --- Step: multi_scan ---
[18:42:50]: ------------------------

+----------------------+----------------------+
| Summary for multi_scan (test_center v3.6.2) |
+----------------------+----------------------+
| try_count            | 3                    |
+----------------------+----------------------+

[18:42:50]: Successfully loaded '/Users/nobody/Documents/ios/sample/fastlane/Scanfile' 📄

+-------------------+-------------------------+
| Detected Values from './fastlane/Scanfile'  |
+-------------------+-------------------------+
| workspace         | sample.xcworkspace  |
| derived_data_path | ./fastlane/derived_data |
| code_coverage     | true                    |
| clean             | true                    |
| skip_slack        | true                    |
| result_bundle     | TestResults             |
| output_directory  | ./fastlane/test_output  |
+-------------------+-------------------------+

[18:42:50]: $ xcodebuild -showBuildSettings -workspace sample.xcworkspace -scheme UITests -configuration UITest
[18:42:53]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[18:42:57]: Successfully loaded '/Users/nobody/Documents/ios/sample/fastlane/Scanfile' 📄

+-------------------+-------------------------+
| Detected Values from './fastlane/Scanfile'  |
+-------------------+-------------------------+
| workspace         | sample.xcworkspace  |
| derived_data_path | ./fastlane/derived_data |
| code_coverage     | true                    |
| clean             | true                    |
| skip_slack        | true                    |
| result_bundle     | TestResults             |
| output_directory  | ./fastlane/test_output  |
+-------------------+-------------------------+

[18:42:57]: $ xcodebuild -showBuildSettings -workspace sample.xcworkspace -scheme UITests -configuration UITest
[18:43:00]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

+------------------------------------------------+----------------------------------------------------------------+
|                                            Summary for scan 2.115.0                                             |
+------------------------------------------------+----------------------------------------------------------------+
| scheme                                         | UITests                                                        |
| configuration                                  | UITest                                                         |
| output_directory                               | fastlane/test_output                                           |
| devices                                        | ["iPhone 8"]                                                   |
| result_bundle                                  | true                                                           |
| build_for_testing                              | true                                                           |
| workspace                                      | sample.xcworkspace                                         |
| skip_detect_devices                            | false                                                          |
| reset_simulator                                | false                                                          |
| reinstall_app                                  | false                                                          |
| app_identifier                                 | com.sample.sample                                      |
| clean                                          | true                                                           |
| code_coverage                                  | true                                                           |
| open_report                                    | false                                                          |
| output_types                                   | html,junit                                                     |
| buildlog_path                                  | ~/Library/Logs/scan                                            |
| include_simulator_logs                         | false                                                          |
| derived_data_path                              | ./fastlane/derived_data                                        |
| should_zip_build_products                      | false                                                          |
| use_clang_report_name                          | false                                                          |
| disable_concurrent_testing                     | false                                                          |
| skip_build                                     | false                                                          |
| slack_use_webhook_configured_username_and_icon | false                                                          |
| slack_username                                 | fastlane                                                       |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png |
| skip_slack                                     | true                                                           |
| slack_only_on_failure                          | false                                                          |
| fail_build                                     | true                                                           |
| xcode_path                                     | /Applications/Xcode.app                                        |
+------------------------------------------------+----------------------------------------------------------------+

[18:43:05]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace sample.xcworkspace -scheme UITests -configuration UITest -destination 'platform=iOS Simulator,id=0D4A1E0C-AC04-4A46-AE27-7F687E1273BC' -derivedDataPath './fastlane/derived_data' -resultBundlePath 'fastlane/test_output/UITests.test_result' -enableCodeCoverage YES clean build-for-testing | tee '/Users/nobody/Library/Logs/scan/sample-UITests.log' | xcpretty  --report html --output '/Users/nobody/Documents/ios/sample/fastlane/test_output/report.html' --report junit --output '/Users/nobody/Documents/ios/sample/fastlane/test_output/report.junit' --report junit --output '/var/folders/t4/wt43777x4297w8b4_nvft95m0000gp/T/junit_report20190207-67165-4ti00u' 



** TEST EXECUTE FAILED **
[19:28:01]: Exit status: 65
[19:28:01]: Successfully sent Slack notification
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 5 |
| Number of failures | 5 |
+--------------------+---+

[19:28:01]: The run of tests would finish with failures due to fragile tests here.
[19:28:02]: '/Users/nobody/Documents/ios/sample/fastlane/test_output/results-sampleUITests/result.junit' is malformed. Attempting to repair it
[19:28:02]: '/Users/nobody/Documents/ios/sample/fastlane/test_output/results-sampleUITests/result-2.junit' is malformed. Attempting to repair it
[19:28:02]: '/Users/nobody/Documents/ios/sample/fastlane/test_output/results-sampleUITests/result-3.junit' is malformed. Attempting to repair it
[19:28:15]: Finished collating test_result bundle to 'fastlane/test_output/results-sampleUITests/UITests.test_result'
[19:28:15]: There are no tests to run in testable '__xctestrun_metadata__'. Skipping
----------------------------------------+--------------------------------------------------------------------+

[19:28:15]: Generating Test Report with XCTestHTMLReport...
XCTestHTMLReport 1.6.1

Report successfully created at test_output/index.html
[19:28:16]: Generating Test Results file...
Extracting device information...
Preparing log file...
Extracting failing test names (if any)...
Extracting Assertion Failures (if any)...

Extracting device information...
Preparing log file...
Extracting failing test names (if any)...
Extracting Assertion Failures (if any)...





`

**Comment by lyndsey-ferguson** [comment]
Can you include the your Fastfile as well, or a sample? I know that I didn't implement anything that generates a XCTestHTMLReport....

**Comment by SathyaNarayanCodeX** [comment]
Below is the sample fastfile 

```
lane :run_ui_tests do
		test_run_block = lambda do |testrun_info|
    	failed_test_count = testrun_info[:failed].size
 
```   
   ```
 if failed_test_count > 0
    	UI.important('The run of tests would finish with failures due to fragile tests here.')

        try_attempt = testrun_info[:try_count]
    if try_attempt < 3
        UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
      end
    end
  end
  
  begin
  	result = multi_scan(
   	 			try_count: 3,
    			scheme: 'UITests',
    			configuration: "UITest",
    			output_directory: 'fastlane/test_output',
    			output_files: 'result.html,result.junit',
  				output_types: 'junit,html',
				devices: ["iPhone 8"],
				result_bundle: true,
				testrun_completed_block: test_run_block
	)
  	  unless result[:failed_testcount].zero?
    		UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
      end  
      puts "Generating Test Report with XCTestHTMLReport..."
      system( "xchtmlreport -r test_output" )
  	  end
			slack_report("Run UI Tests")
	  end`
```

**Comment by SathyaNarayanCodeX** [comment]
@lyndsey-ferguson  I did an experiment and noticed that before the below step ,there are three test bundles created for each retries. And it has their respective results.

What I did is, aborted here. And copied the test bundles created **before collating** / before the below step.

`[19:28:15]: Finished collating test_result bundle to 'fastlane/test_output/results-sampleUITests/UITests.test_result'`


Then executed the xchtml report command to generate a report and I was able to generate the report with all three run including the pass and Fail.

**_I need help to stop the plugin from collating the results into one. So that I could feed all the testbundles to the xchtml report to generate a beautiful report._**

**Comment by lyndsey-ferguson** [comment]
I don't understand what you are requesting. On the one hand, it seems that you want to _not collate_ the test_result bundles. That would be a *new* feature request.

However, if the reason that you want that feature because the final collated test_result bundle does not include passed cases in your situation, would that not be a *bug*?

I want to make sure I am investing my limited time in the most efficient and correct manner possible. If there is a bug with the collation of test_results, I want to fix that as other people will need this.

If you just want a one-off feature to not collate, that is a lower priority for me, but I can guide you on how to add it (it is very simple).

If you would like a work-around, I suggest copying the test-result bundles to a temporary location after each testrun has completed. See this example code as a starting point:

```
test_run_block = lambda do |testrun_info|
  failed_test_count = testrun_info[:failed].size
  passed_test_count = testrun_info[:passing].size
  try_attempt = testrun_info[:try_count]
  batch = testrun_info[:batch]

  # UI.abort_with_message!('You could conditionally abort')
  UI.message("\ὠA everything is fine, let's continue try #{try_attempt + 1} for batch #{batch}")
end

multi_scan(
  project: File.absolute_path('../AtomicBoy/AtomicBoy.xcodeproj'),
  scheme: 'AtomicBoy',
  try_count: 3,
  batch_count: 2,
  fail_build: false,
  testrun_completed_block: test_run_block
)
```

**Comment by SathyaNarayanCodeX** [comment]
okie, so I would say that definitely its a **bug** and a fix would be helpful for others to use the xchtml report. 

Right now I am using the same workaround to make it work. But then there are three entries of each run in the xchtml report , instead of one.  

It's better if you can fix this and we can make use of it with no mess.

**Comment by lyndsey-ferguson** [comment]
@SathyaNarayanCodeX great. Can you create a bug issue and populate the templated values so that it is complete? If you have a sample project, that would help me fix this even faster.

I believe that you've attached most of the relevant data here, so you could just move it over.

**Comment by lyndsey-ferguson** [comment]
I may close this issue soon: I don't have extra time to work on it and it seems that no one else is experiencing this as an issue.

To help me fix this, please provide a sample project with a sample fastfile.

**Comment by SathyaNarayanCodeX** [comment]
Hi Lyndsey-Ferguson,

Give me a week time and I would send the sample project with fastfile and
necessary details.

Thanks,
Sathya

**Comment by lyndsey-ferguson** [comment]
ok
