### ISSUE TITLE
multi_scan does not return summary in case tests failed 

### ISSUE THREAD

**Issue by v-ahadke** [lyndsey-ferguson/fastlane-plugin-test_center#98]
### New Issue Checklist

- [ ] Updated `fastlane-plugin-test_center` to the latest version
- [ ] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [ ] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [ ] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>result = other_action.multi_scan(
          workspace: "TestMultiScan.xcworkspace",
          try_count: options[:retry],
          fail_build: true,
          scheme: options[:scheme],
          device: "iPhone 8",
          output_directory: "./../build",
          buildlog_path: "./../build/logs/scan",
          output_types: "html,junit",
          output_files: "#{report_file_name}.html,#{report_file_name}.xml",
          only_testing: options[:tests_to_run],
          testrun_completed_block: test_run_block
        )</pre>
</details>

When test fails, caller does not get the summary information because of exception raised before returning summary https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/672607d4cdf5fc5be5c963b41ddac5c502fecf46/lib/fastlane/plugin/test_center/actions/multi_scan.rb#L31

Due to exception with simple log, the caller does not know what actually failed, which tests failed. So it makes difficult to know the error. I need to use `fail_build: true,` to fail the jenkins job. Can we return the `summary` to caller even in case of test failed? Thanks

**Comment by lyndsey-ferguson** [comment]
So, you want to get a build summary in the exception itself? I am using the `UI.test_failure!` method to throw a `FastlaneTestFailure`, which doesn't support bundling in extra data.

My suggestion to you is to turn _off_ `:fail_build`, grab the information from the summary and do with it what you want, then call  `UI.test_failure!` yourself.

For example (**not correct!!!**):
```ruby
multi_scan_summary = other_action.multi_scan(
  workspace: "TestMultiScan.xcworkspace",
  try_count: options[:retry],
  fail_build: true,
  scheme: options[:scheme],
  device: "iPhone 8",
  output_directory: "./../build",
  buildlog_path: "./../build/logs/scan",
  output_types: "html,junit",
  output_files: "#{report_file_name}.html,#{report_file_name}.xml",
 only_testing: options[:tests_to_run],
 testrun_completed_block: test_run_block
)
## Do something with the summary data
UI.message("Here is the summary of multi_scan: #{multi_scan_summary}")
UI.test_failure!("tests failed!") unless multi_scan_summary[:failed].empty?
```

**Comment by lyndsey-ferguson** [comment]
@v-ahadke, can you let me know your thoughts on my question and suggestion above?

**Comment by v-ahadke** [comment]
@lyndsey-ferguson I can use the workaround as mentioned above for now. But I think it should be handled in plugin itself by raising the exception with required data.

**Comment by lyndsey-ferguson** [comment]
@v-ahadke Thanks for confirming the workaround, and I can appreciate your thought that the summary data should be bundled into the exception. However, I disagree: the exception should _only_ contain the information about the problem.

I will close this issue as I don't consider this a bug.

**Comment by v-ahadke** [comment]
@lyndsey-ferguson Sorry if I am not clear with my above comment. Actually I mean to say that may be plugin can return the summary to caller & let caller handle the success/error depending on the values present in summary. I can use `multi_scan_summary[:result]` to check if all tests passed or there are any failures instead of plugin raising the exception using `raise UI.test_failure!('Tests have failed')`.

**Comment by lyndsey-ferguson** [comment]
So, you would like the callback that `multi_scan` accepts to also be called when the entire run is complete, and before the exception is called? We can add a feature request for that.
